package com.homestock.modules.shopping.dto;

import com.homestock.modules.shopping.entity.ShoppingListItem;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ShoppingListItemDto {
    private UUID id;
    private UUID shoppingListId;
    private UUID inventoryItemId;
    private String itemName;
    private UUID categoryId;
    private String categoryName;
    private String categoryIcon;
    private String categoryColor;
    private BigDecimal quantity;
    private String unit;
    private Boolean isCompleted;
    private Boolean isAutoGenerated;
    private UUID addedById;
    private String addedByName;
    private UUID completedById;
    private String completedByName;
    private Instant completedAt;
    private String notes;
    private Instant createdAt;

    public static ShoppingListItemDto fromEntity(ShoppingListItem item) {
        if (item == null) return null;
        return ShoppingListItemDto.builder()
                .id(item.getId())
                .shoppingListId(item.getShoppingList().getId())
                .inventoryItemId(item.getInventoryItem() != null ? item.getInventoryItem().getId() : null)
                .itemName(item.getItemName())
                .categoryId(item.getCategory() != null ? item.getCategory().getId() : null)
                .categoryName(item.getCategory() != null ? item.getCategory().getName() : null)
                .categoryIcon(item.getCategory() != null ? item.getCategory().getIcon() : "category")
                .categoryColor(item.getCategory() != null ? item.getCategory().getColorHex() : "#6366F1")
                .quantity(item.getQuantity())
                .unit(item.getUnit())
                .isCompleted(item.getIsCompleted())
                .isAutoGenerated(item.getIsAutoGenerated())
                .addedById(item.getAddedBy().getId())
                .addedByName(item.getAddedBy().getFullName())
                .completedById(item.getCompletedBy() != null ? item.getCompletedBy().getId() : null)
                .completedByName(item.getCompletedBy() != null ? item.getCompletedBy().getFullName() : null)
                .completedAt(item.getCompletedAt())
                .notes(item.getNotes())
                .createdAt(item.getCreatedAt())
                .build();
    }
}
