package com.homestock.modules.shopping.entity;

import com.homestock.core.common.BaseEntity;
import com.homestock.modules.category.entity.Category;
import com.homestock.modules.inventory.entity.InventoryItem;
import com.homestock.modules.user.entity.User;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.Instant;

@Entity
@Table(name = "shopping_list_items")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ShoppingListItem extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "shopping_list_id", nullable = false)
    private ShoppingList shoppingList;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "inventory_item_id")
    private InventoryItem inventoryItem;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "product_id")
    private com.homestock.modules.product.entity.Product product;

    @Column(name = "barcode", length = 50)
    private String barcode;

    @Column(name = "item_name", nullable = false, length = 150)
    private String itemName;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id")
    private Category category;

    @Builder.Default
    @Column(name = "quantity", nullable = false, precision = 12, scale = 3)
    private BigDecimal quantity = BigDecimal.ONE;

    @Builder.Default
    @Column(name = "unit", nullable = false, length = 20)
    private String unit = "pcs";

    @Builder.Default
    @Column(name = "is_completed", nullable = false)
    private Boolean isCompleted = false;

    @Builder.Default
    @Column(name = "is_auto_generated", nullable = false)
    private Boolean isAutoGenerated = false;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "added_by", nullable = false)
    private User addedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "completed_by")
    private User completedBy;

    @Column(name = "completed_at")
    private Instant completedAt;

    @Column(name = "notes")
    private String notes;

    @Column(name = "preferred_brand", length = 100)
    private String preferredBrand;

    @Column(name = "preferred_package_size", length = 50)
    private String preferredPackageSize;

    @Column(name = "preferred_provider", length = 50)
    private String preferredProvider;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "normalized_product_id")
    private com.homestock.modules.product.entity.Product normalizedProduct;
}
