package com.homestock.modules.notification.dto;

import com.homestock.modules.notification.entity.NotificationChannel;
import com.homestock.modules.notification.entity.NotificationDecisionType;
import com.homestock.modules.notification.entity.NotificationPriority;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * NotificationDecision:
 * The intelligent verdict generated by NotificationDecisionEngine specifying:
 * - Decision: SEND_NOW, SCHEDULE, IN_APP_ONLY, GROUP, SUPPRESS
 * - Channel: PUSH, IN_APP, DIGEST, SILENT
 * - Scheduled Delivery Time (if scheduled for optimal interaction)
 * - Detailed ML scores (urgency, relevance, confidence, action probability, fatigue)
 * - Suppression / Grouping rationale
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class NotificationDecision {

    private NotificationCandidate candidate;
    private NotificationDecisionType decisionType;
    private NotificationChannel channel;
    private NotificationPriority resolvedPriority;

    private String finalTitle;
    private String finalBody;
    private String actionLabel;
    private String actionDeepLink;

    private BigDecimal urgencyScore;
    private BigDecimal relevanceScore;
    private BigDecimal confidenceScore;
    private BigDecimal actionProbability;
    private BigDecimal fatigueScore;
    private BigDecimal finalScore;

    private Instant scheduledFor;
    private String rationale;
    private boolean grouped;
}
