import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:flutter/foundation.dart';
import 'package:uuid/uuid.dart';

import '../../core/constants/api_endpoints.dart';
import '../../core/database/app_database.dart';
import '../../core/database/daos/shopping_dao.dart';
import '../../core/database/daos/sync_dao.dart';
import '../../core/network/api_client.dart';
import '../../core/sync/connectivity_monitor.dart';
import '../../core/sync/sync_engine.dart';
import '../../core/sync/sync_operation.dart';
import 'shopping_model.dart';

const _uuid = Uuid();

/// Offline-first shopping repository.
///
/// All reads come from local SQLite.
/// All writes go to local DB + sync queue.
/// Individual operations are synced (not entire list replacement).
class ShoppingRepository {
  final ShoppingDao _shoppingDao;
  final SyncDao _syncDao;
  final ApiClient _apiClient;
  final SyncEngine _syncEngine;
  final ConnectivityMonitor? _connectivity;

  ShoppingRepository({
    required ShoppingDao shoppingDao,
    required SyncDao syncDao,
    required ApiClient apiClient,
    required SyncEngine syncEngine,
    ConnectivityMonitor? connectivity,
  })  : _shoppingDao = shoppingDao,
        _syncDao = syncDao,
        _apiClient = apiClient,
        _syncEngine = syncEngine,
        _connectivity = connectivity;

  bool get isOnline => _connectivity?.isOnline ?? true;

  // ──── READ (always local) ────

  /// Watch the default shopping list with items as a reactive stream.
  Stream<ShoppingListModel?> watchDefaultList(String homeId) {
    final listStream = _shoppingDao.watchShoppingItemsForHome(homeId);
    return listStream.asyncMap((items) async {
      var list = await _shoppingDao.getDefaultList(homeId);
      list ??= await _shoppingDao.ensureDefaultList(homeId);

      final modelItems = items
          .map((item) => ShoppingItemModel(
                id: item.id,
                shoppingListId: item.shoppingListId,
                inventoryItemId: item.inventoryItemId,
                itemName: item.itemName,
                categoryName: item.categoryName,
                categoryIcon: item.categoryIcon,
                categoryColor: item.categoryColor,
                quantity: item.quantity,
                unit: item.unit,
                isCompleted: item.isCompleted,
                isAutoGenerated: item.isAutoGenerated,
                addedByName: item.addedByName,
                completedByName: item.completedByName,
                completedAt: item.completedAt,
                notes: item.notes,
              ))
          .toList();

      return ShoppingListModel(
        id: list.id,
        homeId: list.homeId,
        name: list.name,
        isDefault: list.isDefault,
        pendingCount: modelItems.where((i) => !i.isCompleted).length,
        completedCount: modelItems.where((i) => i.isCompleted).length,
        items: modelItems,
      );
    });
  }

  /// Get the default list (non-reactive).
  Future<ShoppingListModel?> getDefaultList(String homeId) async {
    var list = await _shoppingDao.getDefaultList(homeId);
    list ??= await _shoppingDao.ensureDefaultList(homeId);

    final items = await _shoppingDao.getShoppingItems(list.id);
    final modelItems = items
        .map((item) => ShoppingItemModel(
              id: item.id,
              shoppingListId: item.shoppingListId,
              inventoryItemId: item.inventoryItemId,
              itemName: item.itemName,
              categoryName: item.categoryName,
              categoryIcon: item.categoryIcon,
              categoryColor: item.categoryColor,
              quantity: item.quantity,
              unit: item.unit,
              isCompleted: item.isCompleted,
              isAutoGenerated: item.isAutoGenerated,
              addedByName: item.addedByName,
              completedByName: item.completedByName,
              completedAt: item.completedAt,
              notes: item.notes,
            ))
        .toList();

    return ShoppingListModel(
      id: list.id,
      homeId: list.homeId,
      name: list.name,
      isDefault: list.isDefault,
      pendingCount: modelItems.where((i) => !i.isCompleted).length,
      completedCount: modelItems.where((i) => i.isCompleted).length,
      items: modelItems,
    );
  }

  /// Ensure a default shopping list exists locally in SQLite.
  Future<LocalShoppingList> ensureDefaultList(String homeId) {
    return _shoppingDao.ensureDefaultList(homeId);
  }

  // ──── WRITE (local-first) ────

  /// Add an item to the shopping list locally and queue for sync.
  Future<ShoppingItemModel> addItem(
    String homeId,
    String? listId, {
    String? inventoryItemId,
    required String itemName,
    String? categoryId,
    String? categoryName,
    String? categoryIcon,
    String? categoryColor,
    required double quantity,
    String unit = 'pcs',
    String? notes,
  }) async {
    final effectiveListId = (listId != null && listId.isNotEmpty)
        ? listId
        : (await _shoppingDao.ensureDefaultList(homeId)).id;
    final itemId = _uuid.v4();
    final operationId = _uuid.v4();
    final now = DateTime.now();

    // 1. Insert locally
    await _shoppingDao.upsertShoppingItem(LocalShoppingListItemsCompanion(
      id: Value(itemId),
      shoppingListId: Value(effectiveListId),
      inventoryItemId: Value(inventoryItemId),
      itemName: Value(itemName),
      categoryName: Value(categoryName),
      categoryIcon: Value(categoryIcon ?? 'category'),
      categoryColor: Value(categoryColor ?? '#6366F1'),
      quantity: Value(quantity),
      unit: Value(unit),
      isCompleted: const Value(false),
      isAutoGenerated: const Value(false),
      addedByName: const Value('You'),
      notes: Value(notes),
      isLocalOnly: const Value(true),
      isDeleted: const Value(false),
      updatedAt: Value(now),
    ));

    // 2. Enqueue sync — individual operation, NOT list replacement
    await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
      operationId: Value(operationId),
      operationType: const Value(SyncOperationType.addShoppingItem),
      entityType: const Value(SyncEntityType.shoppingListItem),
      entityId: Value(itemId),
      payload: Value(jsonEncode({
        'listId': listId,
        'inventoryItemId': inventoryItemId,
        'itemName': itemName,
        'categoryId': categoryId,
        'quantity': quantity,
        'unit': unit,
        'notes': notes,
      })),
      createdAt: Value(now),
      homeId: Value(homeId),
    ));

    // 3. Background sync
    _syncEngine.trySyncImmediate();

    return ShoppingItemModel(
      id: itemId,
      shoppingListId: effectiveListId,
      inventoryItemId: inventoryItemId,
      itemName: itemName,
      categoryName: categoryName,
      categoryIcon: categoryIcon ?? 'category',
      categoryColor: categoryColor ?? '#6366F1',
      quantity: quantity,
      unit: unit,
      isCompleted: false,
      isAutoGenerated: false,
      addedByName: 'You',
      notes: notes,
    );
  }

  /// Toggle a shopping item's completion locally and queue for sync.
  Future<void> toggleItem(String homeId, String listId, String itemId) async {
    final operationId = _uuid.v4();
    final now = DateTime.now();

    // Get current state
    final item = await _shoppingDao.getShoppingItemById(itemId);
    if (item == null) return;

    final newCompleted = !item.isCompleted;

    // 1. Update locally
    await _shoppingDao.toggleShoppingItem(
      itemId,
      newCompleted,
      completedByName: newCompleted ? 'You' : null,
    );

    // 2. Enqueue sync
    await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
      operationId: Value(operationId),
      operationType: const Value(SyncOperationType.toggleShoppingItem),
      entityType: const Value(SyncEntityType.shoppingListItem),
      entityId: Value(itemId),
      payload: Value(jsonEncode({
        'listId': listId,
        'isCompleted': newCompleted,
      })),
      createdAt: Value(now),
      homeId: Value(homeId),
    ));

    // 3. Background sync
    _syncEngine.trySyncImmediate();
  }

  /// Update a shopping item's quantity locally and queue for sync.
  Future<void> updateQuantity(String homeId, String listId, String itemId, double newQuantity) async {
    final operationId = _uuid.v4();
    final now = DateTime.now();

    // 1. Update locally
    await _shoppingDao.updateShoppingItemQuantity(itemId, newQuantity);

    // 2. Enqueue sync
    await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
      operationId: Value(operationId),
      operationType: const Value(SyncOperationType.updateShoppingItem),
      entityType: const Value(SyncEntityType.shoppingListItem),
      entityId: Value(itemId),
      payload: Value(jsonEncode({
        'listId': listId,
        'quantity': newQuantity,
      })),
      createdAt: Value(now),
      homeId: Value(homeId),
    ));

    // 3. Background sync
    _syncEngine.trySyncImmediate();
  }

  /// Delete a shopping item locally and queue for sync.
  Future<void> deleteItem(String homeId, String listId, String itemId) async {
    final operationId = _uuid.v4();
    final now = DateTime.now();

    // 1. Soft delete locally
    await _shoppingDao.softDeleteShoppingItem(itemId);

    // 2. Enqueue sync
    await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
      operationId: Value(operationId),
      operationType: const Value(SyncOperationType.deleteShoppingItem),
      entityType: const Value(SyncEntityType.shoppingListItem),
      entityId: Value(itemId),
      payload: Value(jsonEncode({'listId': listId})),
      createdAt: Value(now),
      homeId: Value(homeId),
    ));

    _syncEngine.trySyncImmediate();
  }

  /// Clear all completed items locally and queue for sync.
  Future<void> clearCompleted(String homeId, String listId) async {
    final operationId = _uuid.v4();
    final now = DateTime.now();

    // 1. Delete completed items locally
    await _shoppingDao.clearCompletedItems(listId);

    // 2. Enqueue sync
    await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
      operationId: Value(operationId),
      operationType: const Value(SyncOperationType.clearCompletedShopping),
      entityType: const Value(SyncEntityType.shoppingList),
      entityId: Value(listId),
      payload: Value(jsonEncode({'listId': listId})),
      createdAt: Value(now),
      homeId: Value(homeId),
    ));

    _syncEngine.trySyncImmediate();
  }

  // ──── REMOTE (for initial load) ────

  /// Fetch from server and populate local DB.
  Future<void> fetchAndCacheFromServer(String homeId) async {
    if (_connectivity != null && !_connectivity.isOnline) return;
    try {
      final response = await _apiClient.dio
          .get(ApiEndpoints.defaultShoppingList(homeId));
      final data = response.data['data'];
      if (data == null) return;

      // Upsert the list
      await _shoppingDao.upsertShoppingList(LocalShoppingListsCompanion(
        id: Value(data['id'] as String),
        homeId: Value(homeId),
        name: Value(data['name'] as String? ?? 'Home Shopping List'),
        isDefault: Value(data['isDefault'] as bool? ?? true),
        updatedAt: Value(DateTime.now()),
      ));

      // Upsert items
      final rawItems = data['items'] as List? ?? [];
      final companions = rawItems.map((json) {
        return LocalShoppingListItemsCompanion(
          id: Value(json['id'] as String),
          shoppingListId: Value(json['shoppingListId'] as String? ?? data['id'] as String),
          inventoryItemId: Value(json['inventoryItemId'] as String?),
          itemName: Value(json['itemName'] as String? ?? ''),
          categoryName: Value(json['categoryName'] as String?),
          categoryIcon: Value(json['categoryIcon'] as String? ?? 'category'),
          categoryColor: Value(json['categoryColor'] as String? ?? '#6366F1'),
          quantity: Value((json['quantity'] as num?)?.toDouble() ?? 1.0),
          unit: Value(json['unit'] as String? ?? 'pcs'),
          isCompleted: Value(json['isCompleted'] as bool? ?? false),
          isAutoGenerated: Value(json['isAutoGenerated'] as bool? ?? false),
          addedByName: Value(json['addedByName'] as String? ?? ''),
          completedByName: Value(json['completedByName'] as String?),
          completedAt: Value(json['completedAt'] as String?),
          notes: Value(json['notes'] as String?),
          isLocalOnly: const Value(false),
          isDeleted: const Value(false),
          updatedAt: Value(DateTime.now()),
        );
      }).toList();

      await _shoppingDao.upsertShoppingItems(companions);
    } catch (e) {
      if (kDebugMode) print('[ShoppingRepo] Fetch from server failed: $e');
    }
  }
}
