class ShoppingItemModel {
  final String id;
  final String shoppingListId;
  final String? inventoryItemId;
  final String itemName;
  final String? categoryName;
  final String categoryIcon;
  final String categoryColor;
  final double quantity;
  final String unit;
  final bool isCompleted;
  final bool isAutoGenerated;
  final String addedByName;
  final String? completedByName;
  final String? completedAt;
  final String? notes;

  ShoppingItemModel({
    required this.id,
    required this.shoppingListId,
    this.inventoryItemId,
    required this.itemName,
    this.categoryName,
    required this.categoryIcon,
    required this.categoryColor,
    required this.quantity,
    required this.unit,
    required this.isCompleted,
    required this.isAutoGenerated,
    required this.addedByName,
    this.completedByName,
    this.completedAt,
    this.notes,
  });

  factory ShoppingItemModel.fromJson(Map<String, dynamic> json) {
    return ShoppingItemModel(
      id: json['id'] ?? '',
      shoppingListId: json['shoppingListId'] ?? '',
      inventoryItemId: json['inventoryItemId'],
      itemName: json['itemName'] ?? '',
      categoryName: json['categoryName'],
      categoryIcon: json['categoryIcon'] ?? 'category',
      categoryColor: json['categoryColor'] ?? '#6366F1',
      quantity: (json['quantity'] as num?)?.toDouble() ?? 1.0,
      unit: json['unit'] ?? 'pcs',
      isCompleted: json['isCompleted'] ?? false,
      isAutoGenerated: json['isAutoGenerated'] ?? false,
      addedByName: json['addedByName'] ?? '',
      completedByName: json['completedByName'],
      completedAt: json['completedAt'],
      notes: json['notes'],
    );
  }

  ShoppingItemModel copyWith({bool? isCompleted, String? completedByName}) {
    return ShoppingItemModel(
      id: id,
      shoppingListId: shoppingListId,
      inventoryItemId: inventoryItemId,
      itemName: itemName,
      categoryName: categoryName,
      categoryIcon: categoryIcon,
      categoryColor: categoryColor,
      quantity: quantity,
      unit: unit,
      isCompleted: isCompleted ?? this.isCompleted,
      isAutoGenerated: isAutoGenerated,
      addedByName: addedByName,
      completedByName: completedByName ?? this.completedByName,
      completedAt: completedAt,
      notes: notes,
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'shoppingListId': shoppingListId,
    'inventoryItemId': inventoryItemId,
    'itemName': itemName,
    'categoryName': categoryName,
    'categoryIcon': categoryIcon,
    'categoryColor': categoryColor,
    'quantity': quantity,
    'unit': unit,
    'isCompleted': isCompleted,
    'isAutoGenerated': isAutoGenerated,
    'addedByName': addedByName,
    'completedByName': completedByName,
    'completedAt': completedAt,
    'notes': notes,
  };
}

class ShoppingListModel {
  final String id;
  final String homeId;
  final String name;
  final bool isDefault;
  final int pendingCount;
  final int completedCount;
  final List<ShoppingItemModel> items;

  ShoppingListModel({
    required this.id,
    required this.homeId,
    required this.name,
    required this.isDefault,
    required this.pendingCount,
    required this.completedCount,
    required this.items,
  });

  factory ShoppingListModel.fromJson(Map<String, dynamic> json) {
    final rawItems = json['items'] as List? ?? [];
    return ShoppingListModel(
      id: json['id'] ?? '',
      homeId: json['homeId'] ?? '',
      name: json['name'] ?? '',
      isDefault: json['isDefault'] ?? true,
      pendingCount: json['pendingCount'] ?? 0,
      completedCount: json['completedCount'] ?? 0,
      items: rawItems.map((item) => ShoppingItemModel.fromJson(item)).toList(),
    );
  }

  Map<String, dynamic> toJson() => {
    'id': id,
    'homeId': homeId,
    'name': name,
    'isDefault': isDefault,
    'pendingCount': pendingCount,
    'completedCount': completedCount,
    'items': items.map((i) => i.toJson()).toList(),
  };
}
