import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:flutter/foundation.dart';
import 'package:uuid/uuid.dart';

import '../../core/constants/api_endpoints.dart';
import '../../core/database/app_database.dart';
import '../../core/database/daos/inventory_dao.dart';
import '../../core/database/daos/shopping_dao.dart';
import '../../core/database/daos/sync_dao.dart';
import '../../core/network/api_client.dart';
import '../../core/sync/connectivity_monitor.dart';
import '../../core/sync/sync_engine.dart';
import '../../core/sync/sync_operation.dart';
import 'shopping_model.dart';

const _uuid = Uuid();

/// Offline-first shopping repository.
///
/// All reads come from local SQLite.
/// All writes go to local DB + sync queue.
/// Individual operations are synced (not entire list replacement).
class ShoppingRepository {
  final ShoppingDao _shoppingDao;
  final SyncDao _syncDao;
  final ApiClient _apiClient;
  final SyncEngine _syncEngine;
  final ConnectivityMonitor? _connectivity;
  final InventoryDao? _inventoryDao;
  final AppDatabase? _db;

  ShoppingRepository({
    required ShoppingDao shoppingDao,
    required SyncDao syncDao,
    required ApiClient apiClient,
    required SyncEngine syncEngine,
    ConnectivityMonitor? connectivity,
    InventoryDao? inventoryDao,
    AppDatabase? database,
  })  : _shoppingDao = shoppingDao,
        _syncDao = syncDao,
        _apiClient = apiClient,
        _syncEngine = syncEngine,
        _connectivity = connectivity,
        _inventoryDao = inventoryDao,
        _db = database;

  Future<T> _runInTransaction<T>(Future<T> Function() action) async {
    if (_db != null) {
      return _db.transaction(action);
    }
    return action();
  }

  bool get isOnline => _connectivity?.isOnline ?? true;

  // ──── READ (always local) ────

  /// Watch the default shopping list with items as a reactive stream.
  Stream<ShoppingListModel?> watchDefaultList(String homeId) {
    final listStream = _shoppingDao.watchShoppingItemsForHome(homeId);
    return listStream.asyncMap((items) async {
      var list = await _shoppingDao.getDefaultList(homeId);
      list ??= await _shoppingDao.ensureDefaultList(homeId);

      final modelItems = items
          .map((item) => ShoppingItemModel(
                id: item.id,
                shoppingListId: item.shoppingListId,
                inventoryItemId: item.inventoryItemId,
                itemName: item.itemName,
                categoryName: item.categoryName,
                categoryIcon: item.categoryIcon,
                categoryColor: item.categoryColor,
                quantity: item.quantity,
                unit: item.unit,
                isCompleted: item.isCompleted,
                isAutoGenerated: item.isAutoGenerated,
                addedByName: item.addedByName,
                completedByName: item.completedByName,
                completedAt: item.completedAt,
                notes: item.notes,
                barcode: item.barcode,
                productId: item.productId,
              ))
          .toList();

      return ShoppingListModel(
        id: list.id,
        homeId: list.homeId,
        name: list.name,
        isDefault: list.isDefault,
        pendingCount: modelItems.where((i) => !i.isCompleted).length,
        completedCount: modelItems.where((i) => i.isCompleted).length,
        items: modelItems,
      );
    });
  }

  /// Get the default list (non-reactive).
  Future<ShoppingListModel?> getDefaultList(String homeId) async {
    var list = await _shoppingDao.getDefaultList(homeId);
    list ??= await _shoppingDao.ensureDefaultList(homeId);

    final items = await _shoppingDao.getShoppingItemsForHome(homeId);
    final modelItems = items
        .map((item) => ShoppingItemModel(
              id: item.id,
              shoppingListId: item.shoppingListId,
              inventoryItemId: item.inventoryItemId,
              itemName: item.itemName,
              categoryName: item.categoryName,
              categoryIcon: item.categoryIcon,
              categoryColor: item.categoryColor,
              quantity: item.quantity,
              unit: item.unit,
              isCompleted: item.isCompleted,
              isAutoGenerated: item.isAutoGenerated,
              addedByName: item.addedByName,
              completedByName: item.completedByName,
              completedAt: item.completedAt,
              notes: item.notes,
              barcode: item.barcode,
              productId: item.productId,
            ))
        .toList();

    return ShoppingListModel(
      id: list.id,
      homeId: list.homeId,
      name: list.name,
      isDefault: list.isDefault,
      pendingCount: modelItems.where((i) => !i.isCompleted).length,
      completedCount: modelItems.where((i) => i.isCompleted).length,
      items: modelItems,
    );
  }

  /// Ensure a default shopping list exists locally in SQLite.
  Future<LocalShoppingList> ensureDefaultList(String homeId) {
    return _shoppingDao.ensureDefaultList(homeId);
  }

  /// Resolve an existing fallback home ID if none is active in controller state.
  Future<String?> resolveFallbackHomeId() {
    return _shoppingDao.resolveFallbackHomeId();
  }

  /// Clean up legacy invalid records.
  Future<void> cleanupLegacyDefaultHome() {
    return _shoppingDao.cleanupLegacyDefaultHome();
  }

  // ──── WRITE (local-first) ────

  /// Add an item to the shopping list locally and queue for sync.
  /// Automatically connects to matching inventory item in the active home if one exists!
  Future<ShoppingItemModel> addItem(
    String homeId,
    String? listId, {
    String? inventoryItemId,
    required String itemName,
    String? categoryId,
    String? categoryName,
    String? categoryIcon,
    String? categoryColor,
    required double quantity,
    String unit = 'pcs',
    String? notes,
  }) async {
    final defaultList = await _shoppingDao.ensureDefaultList(homeId);
    final effectiveListId = (listId != null && listId.isNotEmpty)
        ? listId
        : defaultList.id;
    final itemId = _uuid.v4();
    final operationId = _uuid.v4();
    final now = DateTime.now();

    // Auto-connect with existing inventory item if not already supplied
    String? effectiveInventoryItemId = inventoryItemId;
    final invDao = _inventoryDao;
    if ((effectiveInventoryItemId == null || effectiveInventoryItemId.isEmpty) && invDao != null) {
      final existingInv = await invDao.findItemByName(homeId, itemName);
      if (existingInv != null) {
        effectiveInventoryItemId = existingInv.id;
        categoryName ??= existingInv.categoryName;
        categoryIcon ??= existingInv.categoryIcon;
        categoryColor ??= existingInv.categoryColor;
      }
    }

    // 1. Insert locally and enqueue sync atomically
    await _runInTransaction(() async {
      await _shoppingDao.upsertShoppingItem(LocalShoppingListItemsCompanion(
        id: Value(itemId),
        shoppingListId: Value(effectiveListId),
        inventoryItemId: Value(effectiveInventoryItemId),
        itemName: Value(itemName),
        categoryName: Value(categoryName),
        categoryIcon: Value(categoryIcon ?? 'category'),
        categoryColor: Value(categoryColor ?? '#6366F1'),
        quantity: Value(quantity),
        unit: Value(unit),
        isCompleted: const Value(false),
        isAutoGenerated: const Value(false),
        addedByName: const Value('You'),
        notes: Value(notes),
        isLocalOnly: const Value(true),
        isDeleted: const Value(false),
        updatedAt: Value(now),
      ));

      // 2. Enqueue sync — individual operation, NOT list replacement
      await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
        operationId: Value(operationId),
        operationType: const Value(SyncOperationType.addShoppingItem),
        entityType: const Value(SyncEntityType.shoppingListItem),
        entityId: Value(itemId),
        payload: Value(jsonEncode({
          'listId': listId,
          'inventoryItemId': effectiveInventoryItemId,
          'itemName': itemName,
          'categoryId': categoryId,
          'quantity': quantity,
          'unit': unit,
          'notes': notes,
        })),
        createdAt: Value(now),
        homeId: Value(homeId),
      ));
    });

    // 3. Background sync
    _syncEngine.trySyncImmediate();

    return ShoppingItemModel(
      id: itemId,
      shoppingListId: effectiveListId,
      inventoryItemId: effectiveInventoryItemId,
      itemName: itemName,
      categoryName: categoryName,
      categoryIcon: categoryIcon ?? 'category',
      categoryColor: categoryColor ?? '#6366F1',
      quantity: quantity,
      unit: unit,
      isCompleted: false,
      isAutoGenerated: false,
      addedByName: 'You',
      notes: notes,
    );
  }

  /// Toggle a shopping item's completion locally and queue for sync.
  /// Automatically updates connected inventory items and clears/resolves low-stock status!
  Future<void> toggleItem(String homeId, String listId, String itemId) async {
    final operationId = _uuid.v4();
    final now = DateTime.now();

    // Get current state
    final item = await _shoppingDao.getShoppingItemById(itemId);
    if (item == null) return;

    final newCompleted = !item.isCompleted;

    await _runInTransaction(() async {
      // 1. Update locally
      await _shoppingDao.toggleShoppingItem(
        itemId,
        newCompleted,
        completedByName: newCompleted ? 'You' : null,
      );

      // 2. Automatically sync with inventory & update low-stock status
      await _syncInventoryOnItemToggle(homeId, item, newCompleted);

      // 3. Enqueue sync
      await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
        operationId: Value(operationId),
        operationType: const Value(SyncOperationType.toggleShoppingItem),
        entityType: const Value(SyncEntityType.shoppingListItem),
        entityId: Value(itemId),
        payload: Value(jsonEncode({
          'listId': listId,
          'isCompleted': newCompleted,
        })),
        createdAt: Value(now),
        homeId: Value(homeId),
      ));
    });

    // 4. Background sync
    _syncEngine.trySyncImmediate();
  }

  /// Automatically updates connected inventory item stock and resolves/sets low-stock status.
  Future<void> _syncInventoryOnItemToggle(
    String homeId,
    LocalShoppingListItem item,
    bool isCompleted,
  ) async {
    final invDao = _inventoryDao;
    if (invDao == null) return;
    final now = DateTime.now();

    // 1. Locate matching inventory item
    LocalInventoryItem? invItem;
    if (item.inventoryItemId != null && item.inventoryItemId!.isNotEmpty) {
      invItem = await invDao.getItemById(item.inventoryItemId!);
    }
    invItem ??= await invDao.findItemByName(homeId, item.itemName);

    if (isCompleted) {
      // ──── ITEM PURCHASED / BOUGHT ────
      if (invItem != null) {
        // Link shopping item if not already linked
        if (item.inventoryItemId != invItem.id) {
          await _shoppingDao.linkInventoryItem(item.id, invItem.id);
        }

        // Unit conversion if needed (e.g. g <-> kg, ml <-> L)
        final effectiveAddedQty = _convertQuantity(
          fromQty: item.quantity,
          fromUnit: item.unit,
          toUnit: invItem.unit,
        );

        final prevQty = invItem.quantity;
        final newQty = prevQty + effectiveAddedQty;
        final newStockStatus = newQty <= 0
            ? 'OUT_OF_STOCK'
            : (newQty <= invItem.minimumQuantity ? 'LOW_STOCK' : 'IN_STOCK');

        // Update local stock in SQLite (clears low stock if newQty > minimumQuantity)
        await invDao.updateLocalStock(invItem.id, newQty, newStockStatus);

        // Record local STOCK_IN audit transaction
        final txId = _uuid.v4();
        await invDao.insertTransaction(LocalStockTransactionsCompanion(
          id: Value(txId),
          inventoryItemId: Value(invItem.id),
          itemName: Value(invItem.name),
          userName: const Value('You'),
          transactionType: const Value('STOCK_IN'),
          quantityChange: Value(effectiveAddedQty),
          previousQuantity: Value(prevQty),
          newQuantity: Value(newQty),
          unit: Value(invItem.unit),
          reason: const Value('Purchased from shopping list'),
          createdAt: Value(now.toIso8601String()),
          isLocalOnly: const Value(true),
        ));

        // Enqueue sync operation for inventory item
        await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
          operationId: Value(_uuid.v4()),
          operationType: const Value('STOCK_IN'),
          entityType: const Value(SyncEntityType.inventoryItem),
          entityId: Value(invItem.id),
          payload: Value(jsonEncode({
            'transactionType': 'STOCK_IN',
            'quantityChange': effectiveAddedQty,
            'reason': 'Purchased from shopping list',
          })),
          createdAt: Value(now),
          homeId: Value(homeId),
        ));
      } else {
        // Item does not exist in inventory yet: automatically create it!
        final newInvId = _uuid.v4();
        const stockStatus = 'IN_STOCK';

        await invDao.upsertItem(LocalInventoryItemsCompanion(
          id: Value(newInvId),
          homeId: Value(homeId),
          name: Value(item.itemName),
          categoryName: Value(item.categoryName ?? 'Other'),
          categoryIcon: Value(item.categoryIcon),
          categoryColor: Value(item.categoryColor),
          quantity: Value(item.quantity),
          unit: Value(item.unit),
          minimumQuantity: const Value(1.0),
          stockStatus: const Value(stockStatus),
          isLocalOnly: const Value(true),
          isDeleted: const Value(false),
          updatedAt: Value(now),
        ));

        await _shoppingDao.linkInventoryItem(item.id, newInvId);

        await invDao.insertTransaction(LocalStockTransactionsCompanion(
          id: Value(_uuid.v4()),
          inventoryItemId: Value(newInvId),
          itemName: Value(item.itemName),
          userName: const Value('You'),
          transactionType: const Value('STOCK_IN'),
          quantityChange: Value(item.quantity),
          previousQuantity: const Value(0.0),
          newQuantity: Value(item.quantity),
          unit: Value(item.unit),
          reason: const Value('Added to inventory via shopping purchase'),
          createdAt: Value(now.toIso8601String()),
          isLocalOnly: const Value(true),
        ));

        await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
          operationId: Value(_uuid.v4()),
          operationType: const Value('CREATE_ITEM'),
          entityType: const Value(SyncEntityType.inventoryItem),
          entityId: Value(newInvId),
          payload: Value(jsonEncode({
            'name': item.itemName,
            'categoryName': item.categoryName,
            'quantity': item.quantity,
            'unit': item.unit,
            'minimumQuantity': 1.0,
            'stockStatus': stockStatus,
          })),
          createdAt: Value(now),
          homeId: Value(homeId),
        ));
      }
    } else {
      // ──── ITEM UNCHECKED / REVERTED ────
      if (invItem != null) {
        final effectiveDeductedQty = _convertQuantity(
          fromQty: item.quantity,
          fromUnit: item.unit,
          toUnit: invItem.unit,
        );

        final prevQty = invItem.quantity;
        final newQty = (prevQty - effectiveDeductedQty).clamp(0.0, 999999.0);
        final newStockStatus = newQty <= 0
            ? 'OUT_OF_STOCK'
            : (newQty <= invItem.minimumQuantity ? 'LOW_STOCK' : 'IN_STOCK');

        await invDao.updateLocalStock(invItem.id, newQty, newStockStatus);

        await invDao.insertTransaction(LocalStockTransactionsCompanion(
          id: Value(_uuid.v4()),
          inventoryItemId: Value(invItem.id),
          itemName: Value(invItem.name),
          userName: const Value('You'),
          transactionType: const Value('STOCK_OUT'),
          quantityChange: Value(effectiveDeductedQty),
          previousQuantity: Value(prevQty),
          newQuantity: Value(newQty),
          unit: Value(invItem.unit),
          reason: const Value('Unmarked as bought from shopping list'),
          createdAt: Value(now.toIso8601String()),
          isLocalOnly: const Value(true),
        ));

        await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
          operationId: Value(_uuid.v4()),
          operationType: const Value('STOCK_OUT'),
          entityType: const Value(SyncEntityType.inventoryItem),
          entityId: Value(invItem.id),
          payload: Value(jsonEncode({
            'transactionType': 'STOCK_OUT',
            'quantityChange': effectiveDeductedQty,
            'reason': 'Unmarked as bought from shopping list',
          })),
          createdAt: Value(now),
          homeId: Value(homeId),
        ));
      }
    }
  }

  /// Converts quantities when units differ (e.g. 500g -> 0.5kg, 500ml -> 0.5L).
  double _convertQuantity({
    required double fromQty,
    required String fromUnit,
    required String toUnit,
  }) {
    final from = fromUnit.trim().toLowerCase();
    final to = toUnit.trim().toLowerCase();

    if (from == to) return fromQty;

    // Grams to Kilograms
    if (from == 'g' && to == 'kg') return fromQty / 1000.0;
    // Kilograms to Grams
    if (from == 'kg' && to == 'g') return fromQty * 1000.0;
    // Milliliters to Liters
    if (from == 'ml' && (to == 'l' || to == 'litre' || to == 'liter')) return fromQty / 1000.0;
    // Liters to Milliliters
    if ((from == 'l' || from == 'litre' || from == 'liter') && to == 'ml') return fromQty * 1000.0;

    return fromQty;
  }

  /// Batch mark items as completed (e.g. from In-store Shopping Mode or receipt recording).
  Future<void> markItemsCompleted(String homeId, List<String> itemIds, {String? completedByName}) async {
    if (itemIds.isEmpty) return;
    await _runInTransaction(() async {
      await _shoppingDao.markItemsCompleted(itemIds, completedByName: completedByName ?? 'You');
      for (final id in itemIds) {
        final item = await _shoppingDao.getShoppingItemById(id);
        if (item != null) {
          await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
            operationId: Value(_uuid.v4()),
            operationType: const Value(SyncOperationType.toggleShoppingItem),
            entityType: const Value(SyncEntityType.shoppingListItem),
            entityId: Value(id),
            payload: Value(jsonEncode({
              'isCompleted': true,
            })),
            createdAt: Value(DateTime.now()),
            homeId: Value(homeId),
          ));
        }
      }
    });
    _syncEngine.trySyncImmediate();
  }

  /// Update a shopping item's quantity locally and queue for sync.
  Future<void> updateQuantity(String homeId, String listId, String itemId, double newQuantity) async {
    final operationId = _uuid.v4();
    final now = DateTime.now();

    await _runInTransaction(() async {
      // 1. Update locally
      await _shoppingDao.updateShoppingItemQuantity(itemId, newQuantity);

      // 2. Enqueue sync
      await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
        operationId: Value(operationId),
        operationType: const Value(SyncOperationType.updateShoppingItem),
        entityType: const Value(SyncEntityType.shoppingListItem),
        entityId: Value(itemId),
        payload: Value(jsonEncode({
          'listId': listId,
          'quantity': newQuantity,
        })),
        createdAt: Value(now),
        homeId: Value(homeId),
      ));
    });

    // 3. Background sync
    _syncEngine.trySyncImmediate();
  }

  /// Delete a shopping item locally and queue for sync.
  Future<void> deleteItem(String homeId, String listId, String itemId) async {
    final operationId = _uuid.v4();
    final now = DateTime.now();

    await _runInTransaction(() async {
      // 1. Soft delete locally
      await _shoppingDao.softDeleteShoppingItem(itemId);

      // 2. Enqueue sync
      await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
        operationId: Value(operationId),
        operationType: const Value(SyncOperationType.deleteShoppingItem),
        entityType: const Value(SyncEntityType.shoppingListItem),
        entityId: Value(itemId),
        payload: Value(jsonEncode({'listId': listId})),
        createdAt: Value(now),
        homeId: Value(homeId),
      ));
    });

    _syncEngine.trySyncImmediate();
  }

  /// Clear all completed items locally and queue for sync.
  Future<void> clearCompleted(String homeId, String listId) async {
    final operationId = _uuid.v4();
    final now = DateTime.now();

    await _runInTransaction(() async {
      // 1. Delete completed items locally across all home lists
      await _shoppingDao.clearCompletedItemsForHome(homeId);

      // 2. Enqueue sync
      await _syncDao.addToSyncQueue(SyncQueueEntriesCompanion(
        operationId: Value(operationId),
        operationType: const Value(SyncOperationType.clearCompletedShopping),
        entityType: const Value(SyncEntityType.shoppingList),
        entityId: Value(listId),
        payload: Value(jsonEncode({'listId': listId})),
        createdAt: Value(now),
        homeId: Value(homeId),
      ));
    });

    _syncEngine.trySyncImmediate();
  }

  // ──── REMOTE (for initial load) ────

  /// Fetch from server and populate local DB.
  Future<void> fetchAndCacheFromServer(String homeId) async {
    if (homeId.isEmpty || homeId == 'default_home') return;
    if (_connectivity != null && !_connectivity.isOnline) return;
    try {
      final response = await _apiClient.dio
          .get(ApiEndpoints.defaultShoppingList(homeId));
      final data = response.data['data'];
      if (data == null) return;

      final serverListId = data['id'] as String;

      // Upsert the server list
      await _shoppingDao.upsertShoppingList(LocalShoppingListsCompanion(
        id: Value(serverListId),
        homeId: Value(homeId),
        name: Value(data['name'] as String? ?? 'Home Shopping List'),
        isDefault: Value(data['isDefault'] as bool? ?? true),
        updatedAt: Value(DateTime.now()),
      ));

      // If a placeholder local list existed with id == homeId, migrate items to serverListId
      if (serverListId != homeId) {
        await _shoppingDao.migrateItemShoppingListId(homeId, serverListId);
        await _shoppingDao.deleteShoppingListById(homeId);
      }

      // Upsert items
      final rawItems = data['items'] as List? ?? [];
      final companions = rawItems.map((json) {
        return LocalShoppingListItemsCompanion(
          id: Value(json['id'] as String),
          shoppingListId: Value(json['shoppingListId'] as String? ?? serverListId),
          inventoryItemId: Value(json['inventoryItemId'] as String?),
          itemName: Value(json['itemName'] as String? ?? ''),
          categoryName: Value(json['categoryName'] as String?),
          categoryIcon: Value(json['categoryIcon'] as String? ?? 'category'),
          categoryColor: Value(json['categoryColor'] as String? ?? '#6366F1'),
          quantity: Value((json['quantity'] as num?)?.toDouble() ?? 1.0),
          unit: Value(json['unit'] as String? ?? 'pcs'),
          isCompleted: Value(json['isCompleted'] as bool? ?? false),
          isAutoGenerated: Value(json['isAutoGenerated'] as bool? ?? false),
          addedByName: Value(json['addedByName'] as String? ?? ''),
          completedByName: Value(json['completedByName'] as String?),
          completedAt: Value(json['completedAt'] as String?),
          notes: Value(json['notes'] as String?),
          isLocalOnly: const Value(false),
          isDeleted: const Value(false),
          updatedAt: Value(DateTime.now()),
        );
      }).toList();

      await _shoppingDao.upsertShoppingItems(companions);
    } catch (e) {
      if (kDebugMode) print('[ShoppingRepo] Fetch from server failed: $e');
    }
  }
}
