#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Helper generator script to compile comprehensive Fresh Produce, Dairy, Meat & Seafood
expansion items into scripts/expand_fresh_produce_dairy.py.
Target: ~300-350 authentic, high-detail products.
"""

import os
import json

# Definitions of sub-lists
ITEMS = []

def add(item_id, name, tamil, cat, subcat, ptype, unit, sold_by, loc, min_q, q_list, common, aliases, brands, bc_sup, bc_type, loose, pkg, icon):
    ITEMS.append({
        "id": item_id,
        "name": name,
        "tamilName": tamil,
        "category": cat,
        "subCategory": subcat,
        "productType": ptype,
        "defaultUnit": unit,
        "soldBy": sold_by,
        "storageLocation": loc,
        "minimumQuantity": min_q,
        "customQuantities": q_list,
        "commonNames": common,
        "aliases": aliases,
        "brands": brands,
        "barcodeSupport": bc_sup,
        "barcodeType": bc_type,
        "barcodes": [],
        "isLoose": loose,
        "isPackaged": pkg,
        "iconKey": icon
    })

# --- FRESH VEGETABLES (AROMATICS & STAPLES) ---
add("shallots_sambar_onion", "Small Onion / Sambar Shallots", "சின்ன வெங்காயம்", "Fresh Produce", "Fresh Vegetables", "Shallots", "kg", "weight", "Vegetable Basket", 0.5, [0.25, 0.5, 1.0, 2.0], ["Chinna Vengayam", "Sambar Onion", "Small Onion", "Shallots", "Madras Onion"], ["chinna vengayam", "sambar vengayam", "shallots", "small onion"], ["Farm Fresh", "Organic Tattva"], False, "NONE", True, True, "vegetables")
add("bellary_onion_red", "Red Onion", "பெரிய வெங்காயம்", "Fresh Produce", "Fresh Vegetables", "Onion", "kg", "weight", "Vegetable Basket", 1.0, [1.0, 2.0, 3.0, 5.0], ["Periya Vengayam", "Bellary Vengayam", "Pyaz", "Red Onion"], ["big onion", "bellary onion", "periya vengayam", "red onion", "onion"], ["Farm Fresh"], False, "NONE", True, True, "vegetables")
add("white_onion", "White Onion", "வெள்ளை வெங்காயம்", "Fresh Produce", "Fresh Vegetables", "Onion", "kg", "weight", "Vegetable Basket", 0.5, [0.5, 1.0, 2.0], ["Vellai Vengayam", "Safed Pyaz", "White Onion"], ["white onion", "safed pyaz", "vellai vengayam"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("spring_onion_scallions", "Spring Onion / Scallions", "வெங்காயத்தாள்", "Fresh Produce", "Fresh Vegetables", "Onion Greens", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0, 3.0], ["Vengaya Thaal", "Hari Pyaz", "Spring Onion", "Scallions"], ["spring onion", "vengaya thal", "scallions"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("nattu_thakkali_country_tomato", "Country Tomato", "நாட்டுத் தக்காளி", "Fresh Produce", "Fresh Vegetables", "Tomato", "kg", "weight", "Vegetable Tray", 0.5, [0.5, 1.0, 2.0, 3.0], ["Nattu Thakkali", "Desi Tomato", "Sour Tomato", "Country Tomato"], ["desi tomato", "nattu thakkali", "sour tomato"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("hybrid_tomato_bangalore", "Bangalore / Hybrid Tomato", "பெங்களூர் தக்காளி", "Fresh Produce", "Fresh Vegetables", "Tomato", "kg", "weight", "Vegetable Tray", 0.5, [0.5, 1.0, 2.0, 3.0], ["Bangalore Thakkali", "Hybrid Tomato", "Apple Tomato"], ["hybrid tomato", "bangalore tomato", "apple tomato"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("cherry_tomatoes_fresh", "Fresh Cherry Tomatoes", "செர்ரி தக்காளி", "Fresh Produce", "Fresh Vegetables", "Tomato", "g", "weight", "Refrigerator Shelf", 200.0, [200.0, 250.0, 500.0], ["Cherry Tomato", "Small Tomato", "Baby Tomato"], ["cherry tomato", "baby tomato", "salad tomato"], ["Farm Fresh", "Pluckk"], False, "NONE", False, True, "vegetables")
add("potato_regular", "Potato", "உருளைக்கிழங்கு", "Fresh Produce", "Fresh Vegetables", "Potato", "kg", "weight", "Vegetable Basket", 1.0, [1.0, 2.0, 3.0, 5.0], ["Urulaikizhangu", "Aloo", "Potato"], ["potato", "urulaikilangu", "aloo", "batata"], ["Farm Fresh"], False, "NONE", True, True, "vegetables")
add("baby_potato_dum_aloo", "Baby Potato", "சின்ன உருளைக்கிழங்கு", "Fresh Produce", "Fresh Vegetables", "Potato", "kg", "weight", "Vegetable Basket", 0.5, [0.5, 1.0, 2.0], ["Chinna Urulaikizhangu", "Baby Potato", "Dum Aloo Potato"], ["baby potato", "dum aloo potato", "chinna urulaikizhangu"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("ginger_fresh_inji", "Fresh Ginger", "இஞ்சி", "Fresh Produce", "Fresh Vegetables", "Ginger", "g", "weight", "Vegetable Tray", 100.0, [100.0, 250.0, 500.0, 1000.0], ["Inji", "Adrak", "Fresh Ginger"], ["inji", "adrak", "ginger"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("garlic_country_nattu_poondu", "Country Garlic", "நாட்டுப் பூண்டு", "Fresh Produce", "Fresh Vegetables", "Garlic", "g", "weight", "Vegetable Basket", 250.0, [250.0, 500.0, 1000.0], ["Nattu Poondu", "Malai Poondu", "Desi Garlic", "Hill Garlic"], ["nattu poondu", "desi garlic", "poondu", "lahsun"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("garlic_big_cloves", "Garlic Big Cloves", "பெரிய பூண்டு", "Fresh Produce", "Fresh Vegetables", "Garlic", "g", "weight", "Vegetable Basket", 250.0, [250.0, 500.0, 1000.0], ["Periya Poondu", "Big Garlic", "Ooty Garlic"], ["big garlic", "ooty garlic", "mota lahsun"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("green_chili_spicy", "Green Chili Spicy", "காரப் பச்சை மிளகாய்", "Fresh Produce", "Fresh Vegetables", "Chili", "g", "weight", "Vegetable Tray", 100.0, [100.0, 250.0, 500.0], ["Pachai Milagai", "Hari Mirch", "Green Chili"], ["pachai milagai", "hari mirch", "green chili"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("green_chili_mild_bajji", "Bajji Green Chili", "பஜ்ஜி மிளகாய்", "Fresh Produce", "Fresh Vegetables", "Chili", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0], ["Bajji Milagai", "Bhavnagri Mirch", "Stuffing Chili"], ["bajji milagai", "bhavnagri chili", "mild chili"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("fresh_turmeric_root_manjal", "Fresh Turmeric Root", "பச்சை மஞ்சள் கிழங்கு", "Fresh Produce", "Fresh Vegetables", "Root", "g", "weight", "Vegetable Basket", 250.0, [250.0, 500.0], ["Pachai Manjal", "Kacchi Haldi", "Raw Turmeric"], ["pachai manjal", "kacchi haldi", "raw turmeric"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("fresh_mango_ginger_maa_inji", "Fresh Mango Ginger", "மா இஞ்சி", "Fresh Produce", "Fresh Vegetables", "Root", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0], ["Maa Inji", "Amba Haldi", "Mango Ginger"], ["maa inji", "mango ginger", "amba haldi"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")

# --- NAATU KAIKARIGAL & GOURDS ---
add("drumstick_murungaikkai", "Fresh Drumstick", "முருங்கைக்காய்", "Fresh Produce", "Fresh Vegetables", "Drumstick", "piece", "piece", "Vegetable Tray", 2.0, [2.0, 3.0, 5.0, 10.0], ["Murungaikkai", "Sahjan", "Moringa Pods", "Drumstick"], ["murungaikkai", "moringa pod", "sahjan"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("ladies_finger_vendakkai", "Lady's Finger / Okra", "வெண்டைக்காய்", "Fresh Produce", "Fresh Vegetables", "Okra", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Vendakkai", "Bhindi", "Okra"], ["vendakkai", "bhindi", "okra", "ladies finger"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("brinjal_varikkai_striped", "Striped Green Brinjal", "வரி கத்தரிக்காய்", "Fresh Produce", "Fresh Vegetables", "Brinjal", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Vari Katharikai", "Striped Eggplant", "Green Brinjal"], ["vari kathirikai", "striped brinjal", "green brinjal"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("brinjal_purple_round", "Round Purple Brinjal", "ஊதா உருண்டை கத்தரிக்காய்", "Fresh Produce", "Fresh Vegetables", "Brinjal", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Oodha Katharikai", "Baingan", "Eggplant", "Round Brinjal"], ["purple brinjal", "round baingan", "oodha kathirikai"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("brinjal_bhavani_long_purple", "Long Purple Brinjal", "நீள கத்தரிக்காய்", "Fresh Produce", "Fresh Vegetables", "Brinjal", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Neela Katharikai", "Long Eggplant", "Bhavani Kathirikai"], ["long brinjal", "neela kathirikai", "purple eggplant"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("brinjal_udupi_mattu_gulla", "Udupi Mattu Gulla Brinjal", "மட்டு குள்ள கத்தரிக்காய்", "Fresh Produce", "Fresh Vegetables", "Brinjal", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0], ["Mattu Gulla", "Green Round Brinjal"], ["mattu gulla", "udupi brinjal", "green round brinjal"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("bottle_gourd_sorakkai", "Bottle Gourd", "சுரைக்காய்", "Fresh Produce", "Fresh Vegetables", "Gourd", "piece", "piece", "Vegetable Tray", 1.0, [1.0, 2.0], ["Sorakkai", "Lauki", "Ghiya", "Calabash"], ["sorakkai", "lauki", "bottle gourd", "doodhi"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("ridge_gourd_peerkangai", "Ridge Gourd", "பீர்க்கங்காய்", "Fresh Produce", "Fresh Vegetables", "Gourd", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Peerkangai", "Turai", "Luffa", "Ridge Gourd"], ["peerkangai", "turai", "ridge gourd", "dodka"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("snake_gourd_pudalangai", "Snake Gourd", "புடலங்காய்", "Fresh Produce", "Fresh Vegetables", "Gourd", "piece", "piece", "Vegetable Tray", 1.0, [1.0, 2.0], ["Pudalangai", "Chichinda", "Snake Gourd"], ["pudalangai", "snake gourd", "padavalanga"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("bitter_gourd_pavakkai", "Bitter Gourd", "பாகற்காய்", "Fresh Produce", "Fresh Vegetables", "Gourd", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Pavakkai", "Karela", "Bitter Melon", "Bitter Gourd"], ["pavakkai", "karela", "bitter gourd"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("mithi_pavakkai_small_bitter_gourd", "Small Country Bitter Gourd / Mithi Pavakkai", "மிதி பாகற்காய்", "Fresh Produce", "Fresh Vegetables", "Gourd", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0], ["Mithi Pavakkai", "Chhota Karela", "Country Bitter Gourd"], ["mithi pavakkai", "small karela"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("ash_gourd_neer_poosani", "Ash Gourd / Winter Melon", "வெள்ளை பூசணிக்காய்", "Fresh Produce", "Fresh Vegetables", "Gourd", "kg", "weight", "Vegetable Tray", 0.5, [0.5, 1.0, 2.0], ["Vellai Poosanikai", "Neer Poosani", "Petha", "White Pumpkin", "Ash Gourd"], ["ash gourd", "white pumpkin", "neer poosani", "safed petha"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("yellow_pumpkin_parangikai", "Yellow Pumpkin", "மஞ்சள் பூசணிக்காய் / பரங்கிக்காய்", "Fresh Produce", "Fresh Vegetables", "Pumpkin", "kg", "weight", "Vegetable Tray", 0.5, [0.5, 1.0, 2.0], ["Parangikai", "Manjal Poosani", "Kaddu", "Yellow Pumpkin"], ["parangikai", "yellow pumpkin", "kaddu", "red pumpkin"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("chow_chow_chayote", "Chow Chow / Chayote", "சௌ சௌ", "Fresh Produce", "Fresh Vegetables", "Gourd", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Chow Chow", "Chayote", "Bangalore Brinjal", "Mirliton"], ["chow chow", "chayote", "chowchow"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("ivy_gourd_kovakkai_tindora", "Ivy Gourd / Kovakkai", "கோவக்காய்", "Fresh Produce", "Fresh Vegetables", "Gourd", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Kovakkai", "Tindora", "Kundru", "Ivy Gourd"], ["kovakkai", "tindora", "kundru"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("pointed_gourd_parwal", "Pointed Gourd / Parwal", "பர்வால்", "Fresh Produce", "Fresh Vegetables", "Gourd", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0], ["Parwal", "Potala", "Pointed Gourd"], ["parwal", "pointed gourd"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("raw_banana_vazhaikkai", "Raw Cooking Banana", "வாழைக்காய்", "Fresh Produce", "Fresh Vegetables", "Plantain", "piece", "piece", "Vegetable Basket", 2.0, [2.0, 3.0, 5.0], ["Vazhaikkai", "Kaccha Kela", "Raw Plantain", "Green Banana"], ["vazhaikkai", "raw banana", "kaccha kela", "plantain"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("banana_flower_vazhaipoo", "Banana Flower / Plantain Blossom", "வாழைப்பூ", "Fresh Produce", "Fresh Vegetables", "Flower", "piece", "piece", "Vegetable Tray", 1.0, [1.0, 2.0], ["Vazhaipoo", "Kele Ka Phool", "Banana Blossom", "Plantain Flower"], ["vazhaipoo", "banana blossom", "kele ka phool"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("banana_stem_vazhaithandu", "Banana Stem", "வாழைத்தண்டு", "Fresh Produce", "Fresh Vegetables", "Stem", "piece", "piece", "Vegetable Tray", 1.0, [1.0, 2.0], ["Vazhaithandu", "Kele Ka Danda", "Plantain Stem"], ["vazhaithandu", "banana stem", "plantain stem"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("raw_mango_manga", "Raw Green Mango", "பச்சை மாங்காய்", "Fresh Produce", "Fresh Vegetables", "Mango", "piece", "piece", "Vegetable Tray", 1.0, [1.0, 2.0, 5.0], ["Pachai Mangai", "Kaccha Aam", "Raw Mango"], ["manga", "mangai", "kaccha aam", "raw mango"], ["Farm Fresh"], False, "NONE", True, False, "fruits")

# --- BEANS, PEAS & ENGLISH VEGETABLES ---
add("cluster_beans_kothavarangai", "Cluster Beans", "கொத்தவரங்காய்", "Fresh Produce", "Fresh Vegetables", "Beans", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0], ["Kothavarangai", "Gawar Phali", "Guar Beans"], ["kothavarangai", "gawar", "cluster beans"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("broad_beans_avarakkai", "Broad Beans / Country Beans", "அவரைக்காய்", "Fresh Produce", "Fresh Vegetables", "Beans", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Avarakkai", "Sem Phali", "Flat Beans", "Broad Beans"], ["avarakkai", "broad beans", "sem phali"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("french_beans_regular", "French Beans", "பீன்ஸ்", "Fresh Produce", "Fresh Vegetables", "Beans", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Beans", "French Beans", "Green Beans"], ["french beans", "beans", "green beans"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("cowpea_fresh_karamani_kai", "Fresh Long Yard Beans / Karamani", "காராமணி காய்", "Fresh Produce", "Fresh Vegetables", "Beans", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0], ["Karamani Kai", "Lobia Phali", "Yardlong Beans"], ["karamani kai", "yardlong beans", "lobia pods"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("fresh_field_beans_pachai_mochai", "Fresh Field Beans / Mochai", "பச்சை மொச்சை", "Fresh Produce", "Fresh Vegetables", "Beans", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0], ["Pachai Mochai", "Surti Papdi", "Hyacinth Beans"], ["pachai mochai", "fresh mochai", "surti papdi"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("radish_white_mullangi", "White Radish", "முள்ளங்கி", "Fresh Produce", "Fresh Vegetables", "Radish", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Mullangi", "Mooli", "Daikon", "White Radish"], ["mullangi", "mooli", "white radish", "daikon"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("red_radish_round", "Round Red Radish", "சிவப்பு முள்ளங்கி", "Fresh Produce", "Fresh Vegetables", "Radish", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0], ["Sigappu Mullangi", "Lal Mooli", "Red Radish"], ["red radish", "sigappu mullangi"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("carrot_ooty_fresh", "Ooty Fresh Carrot", "ஊட்டி கேரட்", "Fresh Produce", "Fresh Vegetables", "Carrot", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Carrot", "Ooty Carrot", "Gajar", "English Carrot"], ["carrot", "ooty carrot", "gajar"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("beetroot_fresh", "Fresh Beetroot", "பீட்ரூட்", "Fresh Produce", "Fresh Vegetables", "Beetroot", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Beetroot", "Chukandar", "Blood Turnip"], ["beetroot", "chukandar", "beet"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("cabbage_green", "Green Cabbage", "முட்டைக்கோஸ்", "Fresh Produce", "Fresh Vegetables", "Cabbage", "piece", "piece", "Vegetable Tray", 1.0, [1.0, 2.0], ["Muttaikose", "Patta Gobi", "Cabbage"], ["muttaikose", "patta gobi", "cabbage"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("red_cabbage_fresh", "Red Cabbage", "சிவப்பு முட்டைக்கோஸ்", "Fresh Produce", "Fresh Vegetables", "Cabbage", "piece", "piece", "Vegetable Tray", 1.0, [1.0, 2.0], ["Red Cabbage", "Lal Patta Gobi", "Purple Cabbage"], ["red cabbage", "purple cabbage"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("cauliflower_fresh", "Fresh Cauliflower", "காலிஃபிளவர்", "Fresh Produce", "Fresh Vegetables", "Cauliflower", "piece", "piece", "Vegetable Tray", 1.0, [1.0, 2.0], ["Cauliflower", "Phool Gobi", "Gobi"], ["cauliflower", "phool gobi", "gobi"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("broccoli_green_florets", "Fresh Green Broccoli", "ப்ராக்கோலி", "Fresh Produce", "Fresh Vegetables", "Broccoli", "piece", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0], ["Broccoli", "Hari Gobi", "Green Broccoli"], ["broccoli", "green broccoli"], ["Farm Fresh", "Pluckk"], False, "NONE", False, True, "vegetables")
add("green_peas_fresh_pachai_pattani", "Fresh Green Peas", "பச்சைப் பட்டாணி", "Fresh Produce", "Fresh Vegetables", "Peas", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Pachai Pattani", "Matar", "Fresh Peas"], ["green peas", "pachai pattani", "fresh matar"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("capsicum_green_kudaimilagai", "Green Capsicum / Bell Pepper", "பச்சை குடைமிளகாய்", "Fresh Produce", "Fresh Vegetables", "Capsicum", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Kudaimilagai", "Shimla Mirch", "Green Bell Pepper"], ["kudaimilagai", "shimla mirch", "capsicum", "green bell pepper"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("capsicum_colored_red_yellow", "Red and Yellow Bell Peppers", "சிவப்பு & மஞ்சள் குடைமிளகாய்", "Fresh Produce", "Fresh Vegetables", "Capsicum", "piece", "piece", "Vegetable Tray", 1.0, [1.0, 2.0, 4.0], ["Colored Capsicum", "Red Bell Pepper", "Yellow Bell Pepper"], ["red capsicum", "yellow capsicum", "bell pepper mix"], ["Farm Fresh", "Pluckk"], False, "NONE", False, True, "vegetables")
add("cucumber_desi_vellarikkai", "Desi Country Cucumber", "நாட்டு வெள்ளரிக்காய்", "Fresh Produce", "Fresh Vegetables", "Cucumber", "kg", "weight", "Vegetable Tray", 0.5, [0.5, 1.0, 2.0], ["Nattu Vellarikkai", "Desi Kheera", "Country Cucumber"], ["vellarikkai", "desi cucumber", "kheera"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("cucumber_english_seedless", "English Seedless Cucumber", "இங்கிலீஷ் வெள்ளரிக்காய்", "Fresh Produce", "Fresh Vegetables", "Cucumber", "piece", "piece", "Vegetable Tray", 1.0, [1.0, 2.0, 3.0], ["English Kheera", "Seedless Cucumber", "Salad Cucumber"], ["english cucumber", "seedless kheera"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("sweet_corn_cob", "Sweet Corn Cob", "மக்காச்சோளம்", "Fresh Produce", "Fresh Vegetables", "Corn", "piece", "piece", "Vegetable Tray", 1.0, [1.0, 2.0, 4.0], ["Makkacholam", "Makka Bhutta", "Sweet Corn Cob"], ["sweet corn", "corn cob", "bhutta"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("baby_corn_fresh", "Fresh Baby Corn", "பேபி கார்ன்", "Fresh Produce", "Fresh Vegetables", "Corn", "g", "weight", "Refrigerator Shelf", 200.0, [200.0, 400.0], ["Baby Corn", "Chhota Bhutta"], ["baby corn", "chhota bhutta"], ["Farm Fresh", "Pluckk"], False, "NONE", False, True, "vegetables")
add("button_mushrooms_fresh", "Fresh White Button Mushrooms", "காளான்", "Fresh Produce", "Fresh Vegetables", "Mushroom", "g", "weight", "Refrigerator Shelf", 200.0, [200.0, 400.0], ["Kalan", "Khumb", "Button Mushroom"], ["mushroom", "kalan", "button mushroom", "khumb"], ["Farm Fresh", "Pluckk"], False, "NONE", False, True, "vegetables")
add("zucchini_green_fresh", "Fresh Green Zucchini", "பச்சை சுக்கினி", "Fresh Produce", "Fresh Vegetables", "Zucchini", "piece", "piece", "Vegetable Tray", 1.0, [1.0, 2.0], ["Green Zucchini", "Courgette"], ["green zucchini", "courgette"], ["Farm Fresh", "Pluckk"], False, "NONE", False, True, "vegetables")
add("lettuce_iceberg_head", "Fresh Iceberg Lettuce", "லெட்டூஸ் கீரை", "Fresh Produce", "Fresh Vegetables", "Salad Greens", "piece", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0], ["Iceberg Lettuce", "Salad Leaves"], ["iceberg lettuce", "lettuce"], ["Farm Fresh", "Pluckk"], False, "NONE", False, True, "vegetables")

# --- KEERAI & FRESH HERBS ---
add("curry_leaves_karuveppilai", "Fresh Curry Leaves", "கறிவேப்பிலை", "Fresh Produce", "Fresh Herbs & Leaves", "Curry Leaves", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0, 3.0, 5.0], ["Karuveppilai", "Kadi Patta", "Sweet Neem Leaves"], ["karuveppilai", "curry leaf", "kadi patta"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("coriander_leaves_koththamalli", "Fresh Coriander Leaves", "கொத்தமல்லி தழை", "Fresh Produce", "Fresh Herbs & Leaves", "Coriander Leaves", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0, 3.0, 5.0], ["Koththamalli", "Hara Dhaniya", "Cilantro"], ["koththamalli", "dhaniya patta", "cilantro"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("mint_leaves_pudhina", "Fresh Mint Leaves", "புதினா தழை", "Fresh Produce", "Fresh Herbs & Leaves", "Mint Leaves", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0, 3.0], ["Pudhina", "Pudina", "Spearmint Leaves"], ["pudhina", "pudina", "mint leaves"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("arai_keerai_bunch", "Arai Keerai", "அரைக்கீரை", "Fresh Produce", "Leafy Greens", "Keerai", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0, 3.0], ["Arai Keerai", "Amaranth Green"], ["arai keerai", "araikeerai"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("siru_keerai_bunch", "Siru Keerai", "சிறுகீரை", "Fresh Produce", "Leafy Greens", "Keerai", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0, 3.0], ["Siru Keerai", "Small Amaranth"], ["siru keerai", "sirukeerai"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("mulaikeerai_thandu_keerai", "Mulai Keerai / Thandu Keerai", "முளைக்கீரை / தண்டுக்கீரை", "Fresh Produce", "Leafy Greens", "Keerai", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0, 3.0], ["Mulaikeerai", "Thandu Keerai", "Chaulai"], ["mulaikeerai", "thandu keerai", "chaulai saag"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("palak_spinach_fresh", "Fresh Palak / Spinach", "பசலைக்கீரை / பாலக்", "Fresh Produce", "Leafy Greens", "Keerai", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0, 3.0], ["Palak", "Pasalai Keerai", "Spinach"], ["palak", "spinach", "pasalai keerai"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("methi_vendhaya_keerai", "Fresh Methi Leaves", "வெந்தயக்கீரை", "Fresh Produce", "Leafy Greens", "Keerai", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0, 3.0], ["Vendhaya Keerai", "Methi Saag", "Fenugreek Leaves"], ["methi", "vendhaya keerai", "fenugreek leaves"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("murungai_keerai_moringa_leaves", "Moringa / Drumstick Leaves", "முருங்கைக்கீரை", "Fresh Produce", "Leafy Greens", "Keerai", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0, 3.0], ["Murungai Keerai", "Moringa Leaves", "Sahjan Saag"], ["murungai keerai", "moringa leaves", "drumstick leaves"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("ponnanganni_keerai_green", "Ponnanganni Keerai", "பொன்னாங்கண்ணி கீரை", "Fresh Produce", "Leafy Greens", "Keerai", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0], ["Ponnanganni Keerai", "Sessilis Greens"], ["ponnanganni keerai", "ponnanganni"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("manathakkali_keerai_black_nightshade", "Manathakkali Keerai", "மணத்தக்காளி கீரை", "Fresh Produce", "Leafy Greens", "Keerai", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0], ["Manathakkali Keerai", "Black Nightshade Leaves"], ["manathakkali keerai", "manathakkali"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("pulicha_keerai_gongura", "Pulicha Keerai / Gongura", "புளிச்சக்கீரை / கோங்குரா", "Fresh Produce", "Leafy Greens", "Keerai", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0, 3.0], ["Pulicha Keerai", "Gongura Leaves", "Sorrel Leaves"], ["pulicha keerai", "gongura", "sorrel leaves"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("vallarai_keerai_brahmi", "Vallarai Keerai / Brahmi Leaves", "வல்லாரைக்கீரை", "Fresh Produce", "Leafy Greens", "Keerai", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0], ["Vallarai Keerai", "Brahmi Leaves", "Gotu Kola"], ["vallarai keerai", "brahmi leaves"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("mudakathan_keerai", "Mudakathan Keerai", "முடக்கத்தான் கீரை", "Fresh Produce", "Leafy Greens", "Keerai", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0], ["Mudakathan Keerai", "Balloon Vine Leaves"], ["mudakathan keerai", "mudakathan"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("agathi_keerai", "Agathi Keerai", "அகத்திக் கீரை", "Fresh Produce", "Leafy Greens", "Keerai", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0], ["Agathi Keerai", "Sesbania Leaves"], ["agathi keerai", "agathi"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("dill_leaves_sada_kuppi", "Dill Leaves / Sada Kuppi", "சதகுப்பைக் கீரை", "Fresh Produce", "Leafy Greens", "Keerai", "bunch", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0], ["Sada Kuppi", "Suva Saag", "Shepu", "Dill Leaves"], ["dill leaves", "suva saag", "sada kuppi"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")

# --- TUBERS & ROOTS ---
add("elephant_yam_senai_kizhangu", "Elephant Foot Yam", "சேனைக்கிழங்கு", "Fresh Produce", "Tubers & Roots", "Yam", "kg", "weight", "Vegetable Basket", 0.5, [0.5, 1.0, 2.0], ["Senai Kizhangu", "Jimikand", "Suran"], ["senai kizhangu", "jimikand", "suran", "yam"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("colocasia_seppan_kizhangu", "Colocasia / Taro Root", "சேப்பங்கிழங்கு", "Fresh Produce", "Tubers & Roots", "Taro", "g", "weight", "Vegetable Basket", 250.0, [250.0, 500.0, 1000.0], ["Seppan Kizhangu", "Arbi", "Taro Root"], ["seppan kizhangu", "arbi", "taro root"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("sweet_potato_sakkaravalli_kizhangu", "Sweet Potato", "சர்க்கரைவள்ளிக்கிழங்கு", "Fresh Produce", "Tubers & Roots", "Sweet Potato", "g", "weight", "Vegetable Basket", 500.0, [500.0, 1000.0, 2000.0], ["Sakkaravalli Kizhangu", "Shakarkand", "Sweet Potato"], ["sakkaravalli kizhangu", "shakarkand", "sweet potato"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("tapioca_maravalli_kizhangu", "Fresh Tapioca / Cassava", "மரவள்ளிக்கிழங்கு", "Fresh Produce", "Tubers & Roots", "Tapioca", "kg", "weight", "Vegetable Basket", 1.0, [1.0, 2.0, 3.0], ["Maravalli Kizhangu", "Cassava Root", "Kappa"], ["maravalli kizhangu", "tapioca root", "kappa"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")
add("chinese_potato_siru_kizhangu", "Chinese Potato / Koorka", "சிறுகிழங்கு / கூர்க்கா", "Fresh Produce", "Tubers & Roots", "Tuber", "g", "weight", "Vegetable Basket", 250.0, [250.0, 500.0], ["Siru Kizhangu", "Koorka", "Chinese Potato"], ["siru kizhangu", "koorka", "chinese potato"], ["Farm Fresh"], False, "NONE", True, False, "vegetables")

# --- FRESH FRUITS ---
add("banana_yelakki_elaichi", "Yelakki / Elaichi Banana", "ஏலக்கி வாழைப்பழம்", "Fresh Produce", "Fresh Fruits", "Banana", "piece", "piece", "Fruit Basket", 6.0, [6.0, 12.0], ["Yelakki Pazham", "Elaichi Kela", "Small Banana"], ["yelakki banana", "elaichi kela", "yelakki pazham"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("banana_poovan_pazham", "Poovan Banana", "பூவன் வாழைப்பழம்", "Fresh Produce", "Fresh Fruits", "Banana", "piece", "piece", "Fruit Basket", 6.0, [6.0, 12.0], ["Poovan Pazham", "Poovan Banana"], ["poovan banana", "poovan pazham"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("banana_rasthali_pazham", "Rasthali Banana", "ரஸ்தாளி வாழைப்பழம்", "Fresh Produce", "Fresh Fruits", "Banana", "piece", "piece", "Fruit Basket", 6.0, [6.0, 12.0], ["Rasthali Pazham", "Silk Banana", "Rasabale"], ["rasthali banana", "rasthali pazham", "rasabale"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("banana_red_sevvazhai", "Red Banana / Sevvazhai", "செவ்வாழைப்பழம்", "Fresh Produce", "Fresh Fruits", "Banana", "piece", "piece", "Fruit Basket", 3.0, [3.0, 6.0, 12.0], ["Sevvazhai Pazham", "Red Banana", "Lal Kela"], ["red banana", "sevvazhai", "lal kela"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("banana_nendran_kerala", "Nendran Banana", "நேந்திரன் வாழைப்பழம்", "Fresh Produce", "Fresh Fruits", "Banana", "kg", "weight", "Fruit Basket", 0.5, [0.5, 1.0, 2.0], ["Nendran Pazham", "Kerala Banana", "Ethakka"], ["nendran banana", "kerala banana", "nendran pazham"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("banana_robusta_green_cavendish", "Robusta / Cavendish Banana", "ரோபஸ்டா பச்சை வாழைப்பழம்", "Fresh Produce", "Fresh Fruits", "Banana", "piece", "piece", "Fruit Basket", 6.0, [6.0, 12.0], ["Robusta Pazham", "Green Cavendish", "Pachai Vazhai"], ["robusta banana", "green banana", "cavendish banana"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("banana_karpooravalli", "Karpooravalli Banana", "கற்பூரவள்ளி வாழைப்பழம்", "Fresh Produce", "Fresh Fruits", "Banana", "piece", "piece", "Fruit Basket", 6.0, [6.0, 12.0], ["Karpooravalli Pazham", "Sweet Karpura Banana"], ["karpooravalli banana", "karpooravalli"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("mango_alphonso_hapus", "Alphonso Mango", "அல்போன்சா மாம்பழம்", "Fresh Produce", "Fresh Fruits", "Mango", "piece", "piece", "Fruit Basket", 3.0, [3.0, 6.0, 12.0], ["Alphonso Mango", "Hapus Aam"], ["alphonso mango", "hapus mango", "alphonso"], ["Farm Fresh", "Ratnagiri Farms"], False, "NONE", True, True, "fruits")
add("mango_banganapalli_safeda", "Banganapalli / Benishan Mango", "பங்கனப்பள்ளி மாம்பழம்", "Fresh Produce", "Fresh Fruits", "Mango", "kg", "weight", "Fruit Basket", 1.0, [1.0, 2.0, 3.0], ["Banganapalli Aam", "Safeda Mango", "Benishan Mango"], ["banganapalli mango", "safeda mango", "benishan"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("mango_imampasand_himayat", "Imampasand / Himayat Mango", "இமாம்பசந்த் மாம்பழம்", "Fresh Produce", "Fresh Fruits", "Mango", "kg", "weight", "Fruit Basket", 1.0, [1.0, 2.0], ["Imampasand", "Himayat Aam"], ["imampasand mango", "himayat mango"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("mango_malgova", "Malgova Mango", "மல்கோவா மாம்பழம்", "Fresh Produce", "Fresh Fruits", "Mango", "kg", "weight", "Fruit Basket", 1.0, [1.0, 2.0], ["Malgova Mango", "Mulgoba Aam"], ["malgova mango", "mulgoba"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("mango_senthooram", "Senthooram Mango", "செந்தூரம் மாம்பழம்", "Fresh Produce", "Fresh Fruits", "Mango", "kg", "weight", "Fruit Basket", 1.0, [1.0, 2.0], ["Senthooram Aam", "Sindhura Mango"], ["senthooram mango", "sindhura mango"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("mango_kesar_gir", "Gir Kesar Mango", "கேசர் மாம்பழம்", "Fresh Produce", "Fresh Fruits", "Mango", "kg", "weight", "Fruit Basket", 1.0, [1.0, 2.0], ["Kesar Mango", "Gir Kesar Aam"], ["kesar mango", "gir kesar"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("apple_shimla_royal_gala", "Shimla Royal Gala Apple", "சிம்லா ஆப்பிள்", "Fresh Produce", "Fresh Fruits", "Apple", "kg", "weight", "Refrigerator Shelf", 0.5, [0.5, 1.0, 2.0], ["Shimla Apple", "Seb", "Royal Gala"], ["shimla apple", "royal gala apple", "red apple"], ["Farm Fresh"], False, "NONE", True, True, "fruits")
add("apple_granny_smith_green", "Green Apple / Granny Smith", "பச்சை ஆப்பிள்", "Fresh Produce", "Fresh Fruits", "Apple", "piece", "piece", "Refrigerator Shelf", 2.0, [2.0, 4.0], ["Green Apple", "Granny Smith Apple"], ["green apple", "granny smith"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("pomegranate_madhulai", "Fresh Pomegranate", "மாதுளம்பழம்", "Fresh Produce", "Fresh Fruits", "Pomegranate", "kg", "weight", "Fruit Basket", 0.5, [0.5, 1.0, 2.0], ["Madhulampazham", "Anar", "Pomegranate Seeds"], ["pomegranate", "anar", "madhulai"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("papaya_ripe_semi_sweet", "Ripe Papaya", "பப்பாளிப்பழம்", "Fresh Produce", "Fresh Fruits", "Papaya", "piece", "piece", "Fruit Basket", 1.0, [1.0, 2.0], ["Pappali Pazham", "Papita", "Sweet Papaya"], ["papaya", "pappali pazham", "papita"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("guava_koyyapazham_white", "Fresh White Guava", "வெள்ளை கொய்யாப்பழம்", "Fresh Produce", "Fresh Fruits", "Guava", "kg", "weight", "Fruit Basket", 0.5, [0.5, 1.0, 2.0], ["Koyyapazham", "Amrood", "White Guava"], ["guava", "koyyapazham", "amrood"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("guava_pink_taiwan", "Pink Guava", "சிவப்பு கொய்யாப்பழம்", "Fresh Produce", "Fresh Fruits", "Guava", "kg", "weight", "Fruit Basket", 0.5, [0.5, 1.0], ["Pink Guava", "Taiwan Pink Guava"], ["pink guava", "taiwan guava", "red guava"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("sapota_chikoo_round", "Fresh Sapota / Chikoo", "சப்போட்டா பழம்", "Fresh Produce", "Fresh Fruits", "Sapota", "kg", "weight", "Fruit Basket", 0.5, [0.5, 1.0, 2.0], ["Sapota Pazham", "Chikoo", "Sapodilla"], ["sapota", "chikoo", "sapodilla"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("sweet_lime_mosambi", "Sweet Lime / Mosambi", "சாத்துக்குடி", "Fresh Produce", "Fresh Fruits", "Citrus", "kg", "weight", "Fruit Basket", 1.0, [1.0, 2.0, 3.0], ["Sathukudi", "Mosambi", "Sweet Lime"], ["mosambi", "sathukudi", "sweet lime"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("orange_nagpur_mandarin", "Nagpur Orange / Mandarin", "ஆரஞ்சு பழம்", "Fresh Produce", "Fresh Fruits", "Citrus", "kg", "weight", "Fruit Basket", 1.0, [1.0, 2.0], ["Orange Pazham", "Nagpur Santra"], ["orange", "santra", "nagpur orange"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("lemon_country_elumichai", "Country Yellow Lemon", "எலுமிச்சம்பழம்", "Fresh Produce", "Fresh Fruits", "Citrus", "piece", "piece", "Refrigerator Shelf", 3.0, [3.0, 6.0, 12.0], ["Elumichai", "Nimbu", "Yellow Lemon"], ["lemon", "elumichai", "nimbu"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("watermelon_kiran_sweet", "Watermelon Kiran", "தர்பூசணி", "Fresh Produce", "Fresh Fruits", "Melon", "piece", "piece", "Fruit Basket", 1.0, [1.0, 2.0], ["Tharboosani", "Tarbooj", "Kiran Watermelon"], ["watermelon", "tharboosani", "tarbooj"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("muskmelon_kirni_pazham", "Muskmelon / Cantaloupe", "கிர்ணி பழம்", "Fresh Produce", "Fresh Fruits", "Melon", "piece", "piece", "Fruit Basket", 1.0, [1.0, 2.0], ["Kirni Pazham", "Kharbuja", "Muskmelon"], ["muskmelon", "kirni pazham", "kharbuja"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("grapes_green_thompson_seedless", "Green Seedless Grapes", "பச்சை விதை இல்லா திராட்சை", "Fresh Produce", "Fresh Fruits", "Grapes", "g", "weight", "Refrigerator Shelf", 500.0, [500.0, 1000.0], ["Pachai Drakshai", "Green Grapes", "Thompson Seedless"], ["green grapes", "angoor", "seedless grapes"], ["Farm Fresh"], False, "NONE", False, True, "fruits")
add("grapes_black_sharad_seedless", "Black Seedless Grapes", "கருப்பு விதை இல்லா திராட்சை", "Fresh Produce", "Fresh Fruits", "Grapes", "g", "weight", "Refrigerator Shelf", 500.0, [500.0, 1000.0], ["Karuppu Drakshai", "Black Grapes", "Sharad Seedless"], ["black grapes", "kala angoor"], ["Farm Fresh"], False, "NONE", False, True, "fruits")
add("jackfruit_ripe_bulbs", "Ripe Jackfruit Bulbs", "பலாப்பழ சுளைகள்", "Fresh Produce", "Fresh Fruits", "Jackfruit", "g", "weight", "Refrigerator Shelf", 250.0, [250.0, 500.0], ["Palappazham", "Kathal Paka", "Jackfruit Pods"], ["jackfruit", "palappazham", "kathal"], ["Farm Fresh"], False, "NONE", False, True, "fruits")
add("custard_apple_seethapazham", "Custard Apple / Seethapazham", "சீத்தாப்பழம்", "Fresh Produce", "Fresh Fruits", "Fruit", "kg", "weight", "Fruit Basket", 0.5, [0.5, 1.0], ["Seethapazham", "Sitaphal", "Sharifa"], ["custard apple", "seethapazham", "sitaphal"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("pineapple_queen_fresh", "Fresh Sweet Pineapple", "அன்னாசிப்பழம்", "Fresh Produce", "Fresh Fruits", "Pineapple", "piece", "piece", "Fruit Basket", 1.0, [1.0, 2.0], ["Annasi Pazham", "Ananas", "Queen Pineapple"], ["pineapple", "annasi", "ananas"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("dragon_fruit_white_flesh", "White Flesh Dragon Fruit", "டிராகன் பழம்", "Fresh Produce", "Fresh Fruits", "Exotic Fruit", "piece", "piece", "Refrigerator Shelf", 1.0, [1.0, 2.0], ["Dragon Fruit", "Pitaya"], ["dragon fruit", "pitaya"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("kiwi_green_pack", "Green Kiwi Fruit", "கிவி பழம்", "Fresh Produce", "Fresh Fruits", "Exotic Fruit", "piece", "piece", "Refrigerator Shelf", 3.0, [3.0, 6.0], ["Kiwi", "Green Kiwi"], ["kiwi", "green kiwi"], ["Farm Fresh", "Zespri"], False, "NONE", False, True, "fruits")
add("amla_periya_nellikai", "Big Indian Gooseberry / Amla", "பெரிய நெல்லிக்காய்", "Fresh Produce", "Fresh Fruits", "Berry", "g", "weight", "Vegetable Tray", 250.0, [250.0, 500.0, 1000.0], ["Nellikai", "Amla", "Indian Gooseberry"], ["nellikai", "amla", "periya nellikai"], ["Farm Fresh"], False, "NONE", True, False, "fruits")
add("fresh_strawberries_box", "Fresh Strawberries Box", "ஸ்ட்ராபெர்ரி", "Fresh Produce", "Fresh Fruits", "Berries", "g", "weight", "Refrigerator Shelf", 200.0, [200.0, 400.0], ["Strawberry", "Mahabaleshwar Strawberry"], ["strawberries", "strawberry"], ["Farm Fresh"], False, "NONE", False, True, "fruits")
add("fresh_blueberries_box", "Fresh Blueberries Imported", "புளூபெர்ரி", "Fresh Produce", "Fresh Fruits", "Berries", "g", "weight", "Refrigerator Shelf", 125.0, [125.0, 250.0], ["Blueberries", "Neelabadari"], ["blueberries", "blueberry"], ["Farm Fresh", "Driscoll's"], False, "NONE", False, True, "fruits")
add("tender_coconut_elaneer", "Fresh Tender Coconut", "இளநீர்", "Fresh Produce", "Fresh Fruits", "Coconut", "piece", "piece", "Fruit Basket", 1.0, [1.0, 2.0, 4.0], ["Elaneer", "Nariyal Pani", "Tender Coconut", "Daab"], ["tender coconut", "elaneer", "nariyal pani", "daab"], ["Farm Fresh"], False, "NONE", True, False, "beverages")
add("raw_coconut_fresh_thengai", "Fresh Husked Coconut", "தேங்காய்", "Fresh Produce", "Fresh Fruits", "Coconut", "piece", "piece", "Vegetable Basket", 1.0, [1.0, 2.0, 5.0], ["Thengai", "Nariyal", "Husked Coconut"], ["coconut", "thengai", "nariyal"], ["Farm Fresh"], False, "NONE", True, False, "groceries")

# --- DAIRY & COLD STORAGE ---
add("toned_milk_pouch", "Pasteurized Toned Milk Pouch", "சமன்படுத்தப்பட்ட பால்", "Dairy & Cold Storage", "Milk & Cream", "Milk", "ml", "volume", "Refrigerator Shelf", 500.0, [500.0, 1000.0], ["Toned Milk", "Blue Pouch Milk"], ["toned milk", "blue packet milk"], ["Aavin", "Amul", "Nandini", "Heritage", "Hatsun", "Milky Mist"], True, "EAN_13", False, True, "dairy")
add("full_cream_milk_orange_pouch", "Full Cream Standardized Milk", "முழு கிரீம் பால்", "Dairy & Cold Storage", "Milk & Cream", "Milk", "ml", "volume", "Refrigerator Shelf", 500.0, [500.0, 1000.0], ["Full Cream Milk", "Orange Pouch Milk", "Gold Milk"], ["full cream milk", "gold milk", "orange packet milk"], ["Aavin", "Amul", "Nandini", "Heritage", "Milky Mist"], True, "EAN_13", False, True, "dairy")
add("a2_cow_milk_fresh_bottle", "Farm Fresh A2 Desi Cow Milk", "ஏ2 நாட்டுப் பசு பால்", "Dairy & Cold Storage", "Milk & Cream", "Milk", "ml", "volume", "Refrigerator Shelf", 1000.0, [500.0, 1000.0], ["A2 Milk", "Desi Cow Milk"], ["a2 milk", "desi cow milk"], ["Country Delight", "Akshayakalpa", "Two Brothers Organic Farms"], True, "EAN_13", False, True, "dairy")
add("buffalo_milk_rich_fat", "Pure Buffalo Milk Pouch", "எருமைப் பால்", "Dairy & Cold Storage", "Milk & Cream", "Milk", "ml", "volume", "Refrigerator Shelf", 500.0, [500.0, 1000.0], ["Buffalo Milk", "Erumpai Paal", "Bhains Ka Doodh"], ["buffalo milk", "erumpai paal"], ["Amul", "Country Delight", "Heritage"], True, "EAN_13", False, True, "dairy")
add("uht_toned_milk_tetra_pack", "UHT Long Life Toned Milk Carton", "டெட்ரா பேக் பால்", "Dairy & Cold Storage", "Milk & Cream", "Milk", "ml", "volume", "Pantry Shelf", 1000.0, [200.0, 1000.0], ["Tetra Pack Milk", "UHT Milk"], ["uht milk", "tetra pack milk"], ["Amul", "Nestle", "Nandini"], True, "EAN_13", False, True, "dairy")
add("lactose_free_toned_milk", "Lactose Free Milk Carton", "லாக்டோஸ் இல்லாத பால்", "Dairy & Cold Storage", "Milk & Cream", "Milk", "ml", "volume", "Refrigerator Shelf", 1000.0, [200.0, 1000.0], ["Lactose Free Milk"], ["lactose free milk"], ["Amul", "Epigamia"], True, "EAN_13", False, True, "dairy")
add("soya_milk_plain_unsweetened", "Unsweetened Soya Milk Carton", "சோயா பால்", "Dairy & Cold Storage", "Milk & Cream", "Plant Milk", "ml", "volume", "Pantry Shelf", 1000.0, [200.0, 1000.0], ["Soy Milk", "Soya Milk"], ["soya milk", "soy milk"], ["Sofit", "Raw Pressery", "Urban Platter"], True, "EAN_13", False, True, "dairy")
add("almond_milk_unsweetened", "Unsweetened Almond Milk Carton", "பாதாம் பால் டெட்ரா பேக்", "Dairy & Cold Storage", "Milk & Cream", "Plant Milk", "ml", "volume", "Pantry Shelf", 1000.0, [200.0, 1000.0], ["Almond Milk", "Badam Milk Carton"], ["almond milk", "badam milk carton"], ["Raw Pressery", "Epigamia", "Urban Platter", "Borges"], True, "EAN_13", False, True, "dairy")
add("fresh_set_curd_dahi_pouch", "Fresh Curd / Pouch Dahi", "பாக்கெட் தயிர்", "Dairy & Cold Storage", "Curd & Yogurt", "Curd", "g", "weight", "Refrigerator Shelf", 400.0, [200.0, 400.0, 500.0, 1000.0], ["Thayir", "Dahi", "Curd Pouch"], ["thayir", "dahi", "curd"], ["Aavin", "Milky Mist", "Hatsun", "Heritage", "Amul", "Nandini"], True, "EAN_13", False, True, "dairy")
add("fresh_set_curd_tub_matka", "Premium Thick Set Curd Tub", "செட் தயிர்", "Dairy & Cold Storage", "Curd & Yogurt", "Curd", "g", "weight", "Refrigerator Shelf", 400.0, [400.0, 1000.0], ["Set Curd", "Thick Dahi Tub"], ["set curd", "thick curd"], ["Milky Mist", "Amul", "Epigamia"], True, "EAN_13", False, True, "dairy")
add("mishti_doi_bengali_sweet_curd", "Mishti Doi Sweet Curd Cup", "மிஷ்டி தோய் இனிப்பு தயிர்", "Dairy & Cold Storage", "Curd & Yogurt", "Curd", "g", "weight", "Refrigerator Shelf", 85.0, [85.0, 100.0, 400.0], ["Mishti Doi", "Sweet Dahi"], ["mishti doi", "sweet curd"], ["Mother Dairy", "Milky Mist", "Amul"], True, "EAN_13", False, True, "dairy")
add("greek_yogurt_natural_plain", "Plain High Protein Greek Yogurt", "கிரேக்க தயிர்", "Dairy & Cold Storage", "Curd & Yogurt", "Yogurt", "g", "weight", "Refrigerator Shelf", 100.0, [90.0, 100.0, 200.0, 400.0], ["Greek Yogurt", "Thick Yogurt"], ["greek yogurt", "protein curd"], ["Epigamia", "Milky Mist", "Amul"], True, "EAN_13", False, True, "dairy")
add("salted_spiced_buttermilk_neer_mor", "Spiced Buttermilk / Masala Chaas", "மசாலா நீர் மோர்", "Dairy & Cold Storage", "Curd & Yogurt", "Buttermilk", "ml", "volume", "Refrigerator Shelf", 200.0, [200.0, 500.0, 1000.0], ["Neer Mor", "Masala Chaas"], ["neer mor", "chaas", "masala chaas"], ["Aavin", "Milky Mist", "Amul", "Nandini"], True, "EAN_13", False, True, "dairy")
add("sweet_lassi_bottle_tetra", "Sweet Lassi", "இனிப்பு லஸ்ஸி", "Dairy & Cold Storage", "Curd & Yogurt", "Lassi", "ml", "volume", "Refrigerator Shelf", 200.0, [200.0, 250.0], ["Sweet Lassi", "Meethi Lassi"], ["sweet lassi", "lassi"], ["Amul", "Mother Dairy", "Milky Mist"], True, "EAN_13", False, True, "dairy")
add("fresh_malai_paneer_block", "Fresh Malai Paneer Block", "பனீர் கட்டி", "Dairy & Cold Storage", "Paneer & Tofu", "Paneer", "g", "weight", "Refrigerator Shelf", 200.0, [200.0, 500.0, 1000.0], ["Paneer Block", "Malai Paneer"], ["paneer", "malai paneer"], ["Milky Mist", "Amul", "Nandini", "Aavin"], True, "EAN_13", False, True, "dairy")
add("diced_paneer_cubes_fresh", "Diced Paneer Cubes", "நறுக்கிய பனீர் துண்டுகள்", "Dairy & Cold Storage", "Paneer & Tofu", "Paneer", "g", "weight", "Refrigerator Shelf", 200.0, [200.0, 500.0], ["Paneer Cubes", "Diced Paneer"], ["paneer cubes", "cut paneer"], ["Milky Mist", "Amul"], True, "EAN_13", False, True, "dairy")
add("tofu_soya_paneer_block", "Soya Tofu Organic Block", "சோயா டோஃபு", "Dairy & Cold Storage", "Paneer & Tofu", "Tofu", "g", "weight", "Refrigerator Shelf", 200.0, [200.0, 400.0], ["Tofu", "Soya Paneer"], ["tofu", "soya paneer"], ["Milky Mist", "Chetran's", "Urban Platter"], True, "EAN_13", False, True, "dairy")
add("white_cooking_butter_vennai", "Country White Butter / Desi Vennai", "வெள்ளை வெண்ணெய்", "Dairy & Cold Storage", "Butter & Margarine", "Butter", "g", "weight", "Refrigerator Shelf", 200.0, [200.0, 500.0, 1000.0], ["Vellai Vennai", "White Butter", "Makhan"], ["white butter", "cooking butter", "vennai"], ["Aavin", "Milky Mist", "Hatsun", "Nandini"], True, "EAN_13", False, True, "dairy")
add("salted_table_butter_block", "Pasteurized Salted Table Butter", "உப்பு வெண்ணெய்", "Dairy & Cold Storage", "Butter & Margarine", "Butter", "g", "weight", "Refrigerator Shelf", 100.0, [100.0, 500.0], ["Table Butter", "Salted Butter"], ["salted butter", "amul butter"], ["Amul", "Milky Mist", "Nandini", "Britannia"], True, "EAN_13", False, True, "dairy")
add("processed_cheese_slices_pack", "Processed Cheese Slices", "சீஸ் துண்டுகள்", "Dairy & Cold Storage", "Cheese", "Cheese", "piece", "package", "Refrigerator Shelf", 10.0, [10.0, 20.0], ["Cheese Slices", "Sandwich Cheese"], ["cheese slices", "sandwich cheese"], ["Amul", "Britannia", "Milky Mist", "Go Cheese"], True, "EAN_13", False, True, "dairy")
add("processed_cheese_cubes_box", "Processed Cheese Cubes Box", "சீஸ் கியூப்ஸ்", "Dairy & Cold Storage", "Cheese", "Cheese", "g", "weight", "Refrigerator Shelf", 200.0, [200.0, 500.0], ["Cheese Cubes", "Amul Cheese Box"], ["cheese cubes", "amul cheese"], ["Amul", "Britannia", "Milky Mist"], True, "EAN_13", False, True, "dairy")
add("shredded_mozzarella_pizza_cheese", "Diced / Shredded Mozzarella Pizza Cheese", "பீட்சா மொஸரெல்லா சீஸ்", "Dairy & Cold Storage", "Cheese", "Cheese", "g", "weight", "Freezer Compartment", 200.0, [200.0, 500.0, 1000.0], ["Mozzarella Cheese", "Pizza Cheese Blend"], ["mozzarella cheese", "pizza cheese"], ["Milky Mist", "Amul", "Go Cheese"], True, "EAN_13", False, True, "dairy")
add("cheese_spread_garlic_herbs", "Garlic & Herb Cheese Spread Tub", "பூண்டு சீஸ் ஸ்பிரெட்", "Dairy & Cold Storage", "Cheese", "Cheese Spread", "g", "weight", "Refrigerator Shelf", 180.0, [180.0, 200.0], ["Cheese Spread", "Garlic Cheese Spread"], ["cheese spread", "amul cheese spread"], ["Amul", "Britannia", "Milky Mist"], True, "EAN_13", False, True, "dairy")
add("dairy_fresh_cooking_cream", "Fresh Dairy Cooking Cream", "ஃப்ரெஷ் கிரீம்", "Dairy & Cold Storage", "Milk & Cream", "Cream", "ml", "volume", "Refrigerator Shelf", 250.0, [250.0, 1000.0], ["Fresh Cream", "Malai", "Cooking Cream"], ["fresh cream", "cooking cream"], ["Amul", "Milky Mist"], True, "EAN_13", False, True, "dairy")
add("unsweetened_khoya_mawa", "Pure Unsweetened Khoya / Mawa", "இனிப்பற்ற கோவா / மாவா", "Dairy & Cold Storage", "Milk & Cream", "Mawa", "g", "weight", "Refrigerator Shelf", 200.0, [200.0, 500.0], ["Khoya", "Mawa", "Palkova Base"], ["khoya", "mawa"], ["Milky Mist", "Aavin", "Nandini", "Amul"], True, "EAN_13", False, True, "dairy")
add("sweetened_condensed_milk_tin", "Sweetened Condensed Milk Tin", "இனிப்பூட்டப்பட்ட கண்டென்ஸ்டு பால்", "Dairy & Cold Storage", "Milk & Cream", "Condensed Milk", "g", "weight", "Pantry Shelf", 400.0, [200.0, 400.0], ["Condensed Milk", "Milkmaid", "Mithaimate"], ["condensed milk", "milkmaid"], ["Nestle", "Amul"], True, "EAN_13", False, True, "dairy")

# --- POULTRY, MEAT, SEAFOOD & EGGS ---
add("chicken_curry_cut_skinless", "Broiler Chicken Curry Cut Skinless", "தோல் நீக்கிய கோழி இறைச்சி", "Meat & Seafood", "Poultry & Chicken", "Chicken", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Chicken Curry Cut", "Kozhi Kari"], ["chicken curry cut", "skinless chicken"], ["Fresh To Home", "Licious", "Suguna"], False, "NONE", True, True, "meat")
add("country_chicken_naatu_kozhi_curry_cut", "Country Chicken / Naatu Kozhi Cut", "நாட்டுக்கோழி இறைச்சி", "Meat & Seafood", "Poultry & Chicken", "Chicken", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Naatu Kozhi", "Desi Murgh", "Country Chicken"], ["naatu kozhi", "desi chicken"], ["Fresh To Home", "Licious"], False, "NONE", True, True, "meat")
add("chicken_boneless_breast_fillet", "Chicken Boneless Breast Fillet", "எலும்பில்லாத கோழி நெஞ்சுக்கறி", "Meat & Seafood", "Poultry & Chicken", "Chicken", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Boneless Chicken", "Breast Fillet"], ["chicken breast", "boneless chicken"], ["Licious", "Fresh To Home", "Suguna"], False, "NONE", False, True, "meat")
add("chicken_drumsticks_fresh", "Chicken Drumsticks Tangdi", "கோழி கால் துண்டுகள்", "Meat & Seafood", "Poultry & Chicken", "Chicken", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Chicken Drumsticks", "Tangdi Kebab Cuts"], ["chicken drumsticks", "tangdi"], ["Licious", "Fresh To Home"], False, "NONE", False, True, "meat")
add("chicken_keema_mince", "Chicken Keema / Minced Meat", "கோழி கொத்துக்கறி", "Meat & Seafood", "Poultry & Chicken", "Chicken", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Chicken Keema", "Kozhi Kothukari"], ["chicken keema", "minced chicken"], ["Licious", "Fresh To Home"], False, "NONE", False, True, "meat")
add("chicken_liver_fresh", "Fresh Chicken Liver", "கோழி ஈரல்", "Meat & Seafood", "Poultry & Chicken", "Chicken Liver", "g", "weight", "Freezer Compartment", 250.0, [250.0, 500.0], ["Chicken Liver", "Kozhi Eeral", "Kaleji"], ["chicken liver", "kozhi eeral"], ["Licious", "Fresh To Home"], False, "NONE", False, True, "meat")
add("mutton_goat_curry_cut_with_bone", "Goat Mutton Curry Cut With Bone", "ஆட்டுக்கறி குழம்பு வெட்டு", "Meat & Seafood", "Mutton & Lamb", "Mutton", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Aattukkari", "Goat Meat", "Mutton Curry Cut"], ["mutton", "aattukkari", "goat meat"], ["Licious", "Fresh To Home"], False, "NONE", True, True, "meat")
add("mutton_goat_boneless", "Goat Mutton Boneless", "எலும்பில்லாத ஆட்டுக்கறி", "Meat & Seafood", "Mutton & Lamb", "Mutton", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Boneless Mutton", "Boneless Goat Meat"], ["boneless mutton", "boneless goat meat"], ["Licious", "Fresh To Home"], False, "NONE", False, True, "meat")
add("mutton_goat_keema_minced", "Goat Mutton Keema / Mince", "ஆட்டுக் கொத்துக்கறி", "Meat & Seafood", "Mutton & Lamb", "Mutton", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Mutton Keema", "Aattu Kothukari"], ["mutton keema", "goat mince"], ["Licious", "Fresh To Home"], False, "NONE", False, True, "meat")
add("mutton_goat_chops_ribs", "Goat Chops / Chaap Ribs", "ஆட்டு விலா எலும்புக்கறி", "Meat & Seafood", "Mutton & Lamb", "Mutton", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Goat Chops", "Mutton Chaap"], ["mutton chops", "goat chops"], ["Licious", "Fresh To Home"], False, "NONE", False, True, "meat")
add("mutton_goat_liver_eerall", "Fresh Goat Liver", "ஆட்டு ஈரல்", "Meat & Seafood", "Mutton & Lamb", "Mutton Liver", "g", "weight", "Freezer Compartment", 250.0, [250.0, 500.0], ["Goat Liver", "Aattu Eeral", "Mutton Kaleji"], ["goat liver", "mutton liver", "aattu eeral"], ["Licious", "Fresh To Home"], False, "NONE", False, True, "meat")
add("mutton_goat_trotters_paya", "Goat Trotters / Paya (Set of 4)", "ஆட்டுக்கால் பாயா", "Meat & Seafood", "Mutton & Lamb", "Mutton", "piece", "piece", "Freezer Compartment", 4.0, [4.0, 8.0], ["Goat Trotters", "Aattukaal", "Paya Legs"], ["mutton paya", "goat trotters", "aattukaal"], ["Licious", "Fresh To Home"], False, "NONE", False, True, "meat")
add("seer_fish_vanjaram_steaks", "Seer Fish / Vanjaram Steaks", "வஞ்சிர மீன் துண்டுகள்", "Meat & Seafood", "Fish & Seafood", "Fish", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Vanjaram", "King Fish", "Surmai Steaks"], ["vanjaram", "seer fish", "surmai", "king fish"], ["Fresh To Home", "Licious"], False, "NONE", True, True, "seafood")
add("red_snapper_sankara_meen", "Red Snapper / Sankara Fish Cleaned", "சங்கரா மீன்", "Meat & Seafood", "Fish & Seafood", "Fish", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Sankara Meen", "Red Snapper"], ["sankara fish", "red snapper", "sankara meen"], ["Fresh To Home", "Licious"], False, "NONE", True, True, "seafood")
add("white_pomfret_vaval_meen", "White Pomfret / Vellai Vaval", "வெள்ளை வாவல் மீன்", "Meat & Seafood", "Fish & Seafood", "Fish", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["White Pomfret", "Vellai Vaval", "Safed Paplet"], ["white pomfret", "vellai vaval", "pomfret"], ["Fresh To Home", "Licious"], False, "NONE", True, True, "seafood")
add("black_pomfret_karuppu_vaval", "Black Pomfret / Karuppu Vaval", "கருப்பு வாவல் மீன்", "Meat & Seafood", "Fish & Seafood", "Fish", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Black Pomfret", "Karuppu Vaval", "Kala Paplet"], ["black pomfret", "karuppu vaval"], ["Fresh To Home", "Licious"], False, "NONE", True, True, "seafood")
add("rohu_fish_cut_steaks", "Freshwater Rohu Fish Steaks", "ரோகு மீன்", "Meat & Seafood", "Fish & Seafood", "Fish", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Rohu Fish", "Rui Maach"], ["rohu fish", "rohu"], ["Fresh To Home", "Licious"], False, "NONE", True, True, "seafood")
add("katla_fish_cut_steaks", "Freshwater Katla Fish Steaks", "கட்லா மீன்", "Meat & Seafood", "Fish & Seafood", "Fish", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Katla Fish", "Bhakur Maach"], ["katla fish", "katla"], ["Fresh To Home", "Licious"], False, "NONE", True, True, "seafood")
add("indian_mackerel_ayilai_meen", "Indian Mackerel / Ayilai Cleaned", "அயிலை மீன்", "Meat & Seafood", "Fish & Seafood", "Fish", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Ayilai Meen", "Bangda", "Indian Mackerel"], ["ayilai fish", "mackerel", "bangda"], ["Fresh To Home", "Licious"], False, "NONE", True, True, "seafood")
add("sardines_mathi_meen", "Fresh Sardines / Mathi Meen Cleaned", "மத்தி மீன்", "Meat & Seafood", "Fish & Seafood", "Fish", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Mathi Meen", "Tarli", "Sardines"], ["mathi fish", "sardines", "tarli"], ["Fresh To Home", "Licious"], False, "NONE", True, True, "seafood")
add("anchovy_fresh_nethili_meen", "Fresh Anchovy / Nethili Cleaned", "பச்சை நெத்திலி மீன்", "Meat & Seafood", "Fish & Seafood", "Fish", "g", "weight", "Freezer Compartment", 250.0, [250.0, 500.0], ["Nethili Meen", "Fresh Anchovy"], ["nethili fish", "fresh anchovy"], ["Fresh To Home", "Licious"], False, "NONE", True, True, "seafood")
add("prawns_medium_cleaned_deveined", "Fresh White Prawns Cleaned & Deveined", "சுத்தம் செய்த இறால்", "Meat & Seafood", "Fish & Seafood", "Prawns", "g", "weight", "Freezer Compartment", 250.0, [250.0, 500.0], ["Eral", "Jhinga", "Shrimp", "Cleaned Prawns"], ["eral", "prawns", "shrimp"], ["Fresh To Home", "Licious"], False, "NONE", False, True, "seafood")
add("tiger_prawns_large_cleaned", "Jumbo Tiger Prawns Cleaned", "பெரிய டைகர் இறால்", "Meat & Seafood", "Fish & Seafood", "Prawns", "g", "weight", "Freezer Compartment", 250.0, [250.0, 500.0], ["Tiger Prawns", "Big Eral", "Jumbo Shrimp"], ["tiger prawns", "big prawns"], ["Fresh To Home", "Licious"], False, "NONE", False, True, "seafood")
add("crab_blue_sea_swimming", "Fresh Blue Sea Crab Cleaned", "நீல நண்டு", "Meat & Seafood", "Fish & Seafood", "Crab", "g", "weight", "Freezer Compartment", 500.0, [500.0, 1000.0], ["Sea Crab", "Neela Nandu", "Kekda"], ["sea crab", "nandu", "blue crab"], ["Fresh To Home", "Licious"], False, "NONE", False, True, "seafood")
add("squid_rings_kanava_meen", "Cleaned Squid Rings / Kanava", "சுத்தம் செய்த கணவாய் மீன்", "Meat & Seafood", "Fish & Seafood", "Squid", "g", "weight", "Freezer Compartment", 250.0, [250.0, 500.0], ["Kanava", "Squid Rings", "Calamari"], ["kanava", "squid", "calamari"], ["Fresh To Home", "Licious"], False, "NONE", False, True, "seafood")
add("dry_fish_nethili_karuvadu", "Dry Anchovy / Nethili Karuvadu", "நெத்திலி கருவாடு", "Meat & Seafood", "Fish & Seafood", "Dry Fish", "g", "weight", "Pantry Shelf", 100.0, [100.0, 250.0, 500.0], ["Nethili Karuvadu", "Dry Anchovy"], ["nethili karuvadu", "dry fish", "karuvadu"], ["Coastal Catch", "Farm Fresh"], False, "NONE", True, True, "seafood")
add("dry_fish_vanjaram_karuvadu", "Dry Seer Fish / Vanjaram Karuvadu", "வஞ்சிரக் கருவாடு", "Meat & Seafood", "Fish & Seafood", "Dry Fish", "g", "weight", "Pantry Shelf", 100.0, [100.0, 250.0], ["Vanjaram Karuvadu", "Dry King Fish"], ["vanjaram karuvadu", "dry vanjaram"], ["Coastal Catch"], False, "NONE", True, True, "seafood")
add("farm_fresh_white_eggs_pack_6", "Farm Fresh White Table Eggs (Pack of 6)", "வெள்ளை முட்டை (6 எண்ணிக்கை)", "Meat & Seafood", "Eggs", "Eggs", "piece", "piece", "Egg Tray", 6.0, [6.0, 12.0, 30.0], ["White Eggs", "Kozhi Muttai", "Anda"], ["eggs", "white eggs", "muttai", "anda"], ["Suguna", "Eggoz", "Farm Fresh"], True, "EAN_13", False, True, "dairy")
add("country_chicken_eggs_naatu_kozhi_muttai", "Country Chicken Eggs / Naatu Kozhi Muttai (Pack of 6)", "நாட்டுக்கோழி முட்டை (6 எண்ணிக்கை)", "Meat & Seafood", "Eggs", "Eggs", "piece", "piece", "Egg Tray", 6.0, [6.0, 12.0], ["Naatu Kozhi Muttai", "Desi Anda", "Country Eggs"], ["naatu kozhi muttai", "desi eggs", "country eggs"], ["Suguna", "Eggoz", "Country Delight"], True, "EAN_13", False, True, "dairy")
add("quail_eggs_kaadai_muttai_pack_12", "Quail Eggs / Kaadai Muttai (Pack of 12)", "காடை முட்டை (12 எண்ணிக்கை)", "Meat & Seafood", "Eggs", "Eggs", "piece", "piece", "Egg Tray", 12.0, [12.0, 24.0], ["Kaadai Muttai", "Bater Ke Ande", "Quail Eggs"], ["quail eggs", "kaadai muttai"], ["Farm Fresh", "Suguna"], True, "EAN_13", False, True, "dairy")

# Write out python file
json_str = json.dumps(ITEMS, ensure_ascii=False)
code = f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import json

"""
Expansion module for Fresh Produce, Dairy, and Meat & Seafood.
Generated with {len(ITEMS)} authentic Indian household items.
"""

_DATA = r"""{json_str}"""

def get_fresh_produce_dairy_expansion():
    return json.loads(_DATA)

if __name__ == "__main__":
    items = get_fresh_produce_dairy_expansion()
    print(f"Loaded {{len(items)}} fresh produce, dairy and meat products.")
'''

with open("scripts/expand_fresh_produce_dairy.py", "w", encoding="utf-8") as f:
    f.write(code)

print(f"Successfully generated scripts/expand_fresh_produce_dairy.py with {len(ITEMS)} items.")
