# Expand Food & Grocery (Rice, Millets, Dals, Pulses, Flours, Sooji, Pasta, Baking)
# Adds ~450 highly curated Indian supermarket and regional products.

def get_food_grocery_expansion():
    items = [
        # --- TRADITIONAL & SPECIALTY RICE VARIETIES ---
        {
            "id": "rice_seeraga_samba",
            "name": "Seeraga Samba Biryani Rice",
            "tamilName": "சீரக சம்பா அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Jeera Samba Rice", "Seeraga Samba Arisi", "Khaima Rice", "South Indian Biryani Rice"],
            "aliases": ["Jeerakasala Rice", "Biryani Rice Tamil", "Dindigul Thalappakatti Rice", "Small Aromatic Rice"],
            "brands": ["Rooster", "Udhayam", "Heritage", "Idhayam", "Double Horse"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 2.0, 5.0, 10.0, 25.0]
        },
        {
            "id": "rice_mappillai_samba",
            "name": "Mappillai Samba Red Rice",
            "tamilName": "மாப்பிள்ளை சம்பா பாரம்பரிய அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Bridegroom Rice", "Mappillai Samba Arisi", "Red Heritage Rice", "High Iron Rice"],
            "aliases": ["Traditional Tamil Red Rice", "Mappillai Samba Unpolished"],
            "brands": ["Isha Arogya", "Organic Tattva", "24 Mantra", "Gramiyum", "Namma Nellu"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "rice_kullakar",
            "name": "Kullakar Traditional Rice",
            "tamilName": "குள்ளக்கார் பாரம்பரிய அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Kullakar Arisi", "Red Medicinal Rice", "Indigenous Tamil Rice"],
            "aliases": ["Kullakar Idli Rice", "Low GI Tamil Rice"],
            "brands": ["Pasumai", "Gramiyum", "Namma Nellu", "Organic Poshan"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "rice_poongar",
            "name": "Poongar Traditional Women's Health Rice",
            "tamilName": "பூங்கார் பாரம்பரிய அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Poongar Arisi", "Maternal Health Rice", "Tamil Traditional Red Rice"],
            "aliases": ["Poongar Porridge Rice", "Hand Pounded Poongar"],
            "brands": ["Gramiyum", "Namma Nellu", "Bio Basics", "Organic Tattva"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "rice_kaiviral_samba",
            "name": "Kaiviral Samba Traditional Rice",
            "tamilName": "கைவிரல் சம்பா அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Finger Rice", "Kaiviral Samba Arisi", "Immunity Red Rice"],
            "aliases": ["Heritage Tamil Rice Kaiviral"],
            "brands": ["Pasumai", "Namma Nellu", "Gramiyum"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "rice_kattuyanam",
            "name": "Kattuyanam Traditional Diabetes Rice",
            "tamilName": "காட்டுயானம் பாரம்பரிய அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Wild Elephant Rice", "Kattuyanam Arisi", "Diabetic Friendly Heritage Rice"],
            "aliases": ["Kattuyanam Porridge Rice", "Kattuyanam Puttu Rice"],
            "brands": ["Gramiyum", "Bio Basics", "Organic Poshan", "Namma Nellu"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "rice_kichili_samba",
            "name": "Kichili Samba Table Rice",
            "tamilName": "கிச்சிலி சம்பா அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Kichili Samba Arisi", "Tasty White Heritage Rice", "South Indian Royal Rice"],
            "aliases": ["Traditional White Ponni Alternative", "Kichili Samba Organic"],
            "brands": ["Namma Nellu", "Gramiyum", "Bio Basics", "Pasumai"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 2.0, 5.0, 10.0]
        },
        {
            "id": "rice_bamboo",
            "name": "Bamboo Rice",
            "tamilName": "மூங்கில் அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 250.0,
            "commonNames": ["Moongil Arisi", "Baans Ka Chawal", "Wild Bamboo Seed Rice", "Mulayari"],
            "aliases": ["Bamboo Paddy", "Forest Bamboo Seed"],
            "brands": ["Natureland", "Gramiyum", "Organic Tattva", "Bio Basics"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [250.0, 500.0, 1000.0]
        },
        {
            "id": "rice_gobindobhog",
            "name": "Gobindobhog Aromatic Rice",
            "tamilName": "கோவிந்தபோக் மண அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Govind Bhog", "Bengal Payesh Rice", "Aromatic Small Grain Rice", "Prasad Rice"],
            "aliases": ["Bengali Kheer Rice", "Gobindobhog Bengali Special"],
            "brands": ["Fortune", "Daawat", "BB Royal", "Dheki", "Organic Tattva"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "rice_wada_kolam",
            "name": "Wada Kolam Rice",
            "tamilName": "வாடா கோலம் அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Zini Rice", "Maharashtra Wada Kolam", "Daily Table Kolam Rice"],
            "aliases": ["Kolam Arisi", "Wada Kolam Tukda"],
            "brands": ["Fortune", "BB Royal", "Mother's Choice", "Samarth"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 5.0, 10.0, 25.0]
        },
        {
            "id": "rice_ambemohar",
            "name": "Ambemohar Fragrant Rice",
            "tamilName": "ஆம்பேமோஹர் நறுமண அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Mango Blossom Rice", "Marathi Ambemohar", "Aromatic Western Ghats Rice"],
            "aliases": ["Ambemohar Kheer Rice", "Polished Ambemohar"],
            "brands": ["Samarth", "Organic Tattva", "BB Royal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "rice_indrayani",
            "name": "Indrayani Soft Fragrant Rice",
            "tamilName": "இந்திராயணி அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Indrayani Chawal", "Sticky Soft Rice", "Maharashtra Indrayani"],
            "aliases": ["Indrayani Scented Rice", "Indrayani Unpolished"],
            "brands": ["BB Royal", "Fortune", "Organic Tattva"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 5.0, 10.0]
        },
        {
            "id": "rice_kalanamak",
            "name": "Kalanamak Buddha Scented Rice",
            "tamilName": "காளாநமக் வாசனை அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Black Salt Rice", "Buddha Rice", "Lord Buddha Scented Rice", "UP Kalanamak"],
            "aliases": ["Aromatic Heritage Kalanamak", "Kala Namak Rice"],
            "brands": ["Natureland", "Organic India", "24 Mantra"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "rice_basmati_1121_sella",
            "name": "1121 Golden Sella Basmati Rice",
            "tamilName": "1121 கோல்டன் செல்லா பாசுமதி அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Golden Parboiled Basmati", "Extra Long Sella Rice", "Pusa 1121 Basmati"],
            "aliases": ["Catering Biryani Basmati", "Yellow Sella Basmati"],
            "brands": ["India Gate", "Daawat", "Fortune", "Kohinoor", "Lal Qilla"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 5.0, 10.0, 25.0]
        },
        {
            "id": "rice_basmati_creamy_sella",
            "name": "Creamy White Sella Basmati Rice",
            "tamilName": "வெள்ளை செல்லா பாசுமதி அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["White Parboiled Basmati", "Creamy Sella Biryani Rice"],
            "aliases": ["Steam Basmati Sella", "Daawat White Sella"],
            "brands": ["India Gate", "Daawat", "Rozana", "Kohinoor"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 5.0, 10.0]
        },
        {
            "id": "rice_basmati_mogra_broken",
            "name": "Basmati Mogra Broken Rice",
            "tamilName": "பாசுமதி மொக்ரா நொய் அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Basmati Tukda", "Mogra Basmati", "Daily Use Basmati Broken"],
            "aliases": ["Basmati Kinki", "Broken Basmati for Pulao/Khichdi"],
            "brands": ["India Gate", "Daawat", "Fortune", "BB Royal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 5.0, 10.0]
        },
        {
            "id": "rice_basmati_dubar",
            "name": "Basmati Dubar Medium Grain Rice",
            "tamilName": "பாசுமதி தூபார் நடுத்தர அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Dubar Basmati", "Half Grain Basmati", "Daily Pulao Rice"],
            "aliases": ["Semi Broken Basmati", "Daawat Dubar"],
            "brands": ["India Gate", "Daawat", "Fortune", "Kohinoor"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 5.0, 10.0]
        },
        {
            "id": "rice_basmati_tibar",
            "name": "Basmati Tibar Three-Quarter Grain Rice",
            "tamilName": "பாசுமதி திபார் அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Tibar Basmati", "3/4th Grain Basmati Rice"],
            "aliases": ["India Gate Tibar", "Daawat Tibar"],
            "brands": ["India Gate", "Daawat", "Fortune"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 5.0, 10.0]
        },
        {
            "id": "rice_idli_gundu",
            "name": "Gundu Idli Parboiled Rice",
            "tamilName": "குண்டு இட்லி அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Round Idli Rice", "Chettinad Idli Arisi", "Fat Grain Idli Rice"],
            "aliases": ["Salem Gundu Idli Rice", "Udhayam Idli Rice"],
            "brands": ["Udhayam", "Naga", "Double Horse", "Heritage", "BB Royal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 5.0, 10.0, 25.0]
        },
        {
            "id": "rice_red_matta_palakkad",
            "name": "Palakkadan Unda Matta Rice",
            "tamilName": "பாலக்காடன் உண்டா மட்டா அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Kerala Matta Rice", "Unda Matta", "Parboiled Red Matta"],
            "aliases": ["Palakkad Matta", "Double Horse Matta Rice", "Pavizham Matta"],
            "brands": ["Double Horse", "Pavizham", "Nirapara", "Kitchen Treasures", "Brahmins"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 5.0, 10.0]
        },
        {
            "id": "rice_red_matta_vadi",
            "name": "Vadi Matta Long Grain Red Rice",
            "tamilName": "வாடி மட்டா நீண்ட சிகப்பரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Long Matta Rice", "Vadi Matta Chawal"],
            "aliases": ["Kerala Vadi Matta", "Double Horse Vadi Matta"],
            "brands": ["Double Horse", "Pavizham", "Nirapara", "Eastern"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 5.0, 10.0]
        },
        {
            "id": "rice_jeerakasala_wayanad",
            "name": "Wayanad Jeerakasala Ghee Rice",
            "tamilName": "வயநாடு சீரகசாலா நெய் சோறு அரிசி",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Khaima Rice", "Malabar Biryani Rice", "Wayanadan Kaima"],
            "aliases": ["Jeerakasala Neychoru Rice", "Thalassery Biryani Rice"],
            "brands": ["Double Horse", "Kitchen Treasures", "Nirapara", "Eastern"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "rice", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "rice_cracked_dalia",
            "name": "Broken Samba Wheat Rava / Dalia",
            "tamilName": "சம்பா கோதுமை ரவை",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Godhumai Rava", "Cracked Wheat Dalia", "Lapsi Rava", "Fada"],
            "aliases": ["Wheat Grits", "Bulgur Wheat Broken", "Diet Dalia"],
            "brands": ["Naga", "Aashirvaad", "Fortune", "Pillsbury", "Anil"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "rice_poha_dagdi",
            "name": "Dagdi Poha / Heavy Flattened Rice",
            "tamilName": "தடிமனான கெட்டி அவல்",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 500.0,
            "commonNames": ["Kanda Poha Flattened Rice", "Maharashtra Dagdi Poha", "Super Thick Aval"],
            "aliases": ["Kanda Batata Poha Rice", "Thick Beaten Rice"],
            "brands": ["Fortune", "Tata Sampann", "BB Royal", "MTR"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [500.0, 1000.0]
        },
        {
            "id": "rice_poha_roasted",
            "name": "Roasted Flattened Rice / Poha Chivda",
            "tamilName": "வறுத்த அவல்",
            "category": "Food & Grocery", "subCategory": "Rice & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 250.0,
            "commonNames": ["Roast Poha", "Bhaad Poha", "Diet Chivda Base Poha"],
            "aliases": ["Oil-free Roasted Poha", "Crunchy Roasted Aval"],
            "brands": ["Haldiram", "Bikano", "BB Royal", "Chitale"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [250.0, 500.0, 1000.0]
        },

        # --- MILLETS (SIRUDHANYA) ---
        {
            "id": "millet_foxtail_thinai",
            "name": "Foxtail Millet Whole Grain",
            "tamilName": "தினை அரிசி",
            "category": "Food & Grocery", "subCategory": "Millets", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Thinai Arisi", "Kangni", "Navane", "Korra", "Kakum"],
            "aliases": ["Unhulled Foxtail Millet", "Organic Thinai Rice"],
            "brands": ["24 Mantra", "Organic Tattva", "True Elements", "Bio Basics", "Patanjali"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "millet_little_samai",
            "name": "Little Millet Grain",
            "tamilName": "சாமை அரிசி",
            "category": "Food & Grocery", "subCategory": "Millets", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Samai Arisi", "Kutki", "Same", "Sama", "Samalu"],
            "aliases": ["Vrat Ka Chawal Alternative", "Organic Samai Rice"],
            "brands": ["24 Mantra", "Organic Tattva", "Bio Basics", "Udhayam", "Patanjali"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "millet_kodo_varagu",
            "name": "Kodo Millet Grain",
            "tamilName": "வரகு அரிசி",
            "category": "Food & Grocery", "subCategory": "Millets", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Varagu Arisi", "Kodra", "Harka", "Arikelu", "Kodo Rice"],
            "aliases": ["Dehusked Kodo Millet", "Diabetic Friendly Varagu"],
            "brands": ["24 Mantra", "Organic Tattva", "Bio Basics", "Udhayam", "Natureland"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "millet_barnyard_kuthiraivali",
            "name": "Barnyard Millet Grain",
            "tamilName": "குதிரைவாலி அரிசி",
            "category": "Food & Grocery", "subCategory": "Millets", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Kuthiraivali Arisi", "Sanwa", "Oodalu", "Udalu", "Jhangora", "Kuthiravali"],
            "aliases": ["Vrat Ke Chawal", "Samak Rice", "Fasting Barnyard Rice"],
            "brands": ["24 Mantra", "Organic Tattva", "Bio Basics", "Natureland", "Patanjali"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "millet_proso_panivaragu",
            "name": "Proso Millet Grain",
            "tamilName": "பனிவரகு அரிசி",
            "category": "Food & Grocery", "subCategory": "Millets", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Panivaragu Arisi", "Chena", "Barri", "Baragu", "Varigalu"],
            "aliases": ["Common Millet", "White Millet Grain", "Panivaragu Organic"],
            "brands": ["24 Mantra", "Organic Tattva", "Bio Basics", "Gramiyum"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "millet_browntop_korale",
            "name": "Browntop Millet Grain",
            "tamilName": "பழுப்பு புல் தினை / பிலா வரகு",
            "category": "Food & Grocery", "subCategory": "Millets", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Korale Millet", "Andu Korralu", "Browntop Rice", "Highest Fiber Millet"],
            "aliases": ["Siridhanya Browntop", "Dr Khadar Vali Browntop Millet"],
            "brands": ["True Elements", "Bio Basics", "24 Mantra", "Organic Tattva"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "millet_pearl_bajra_whole",
            "name": "Whole Pearl Millet / Bajra",
            "tamilName": "கம்பு முழு தானியம்",
            "category": "Food & Grocery", "subCategory": "Millets", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Kambu", "Bajra Grains", "Sajjalu", "Sajje", "Pearl Millet Seeds"],
            "aliases": ["Raw Kambu Seeds", "Desi Bajra Whole"],
            "brands": ["Tata Sampann", "Organic Tattva", "24 Mantra", "Udhayam"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "millet_sorghum_jowar_whole",
            "name": "Whole White Sorghum / Jowar",
            "tamilName": "வெள்ளை சோளம் முழு தானியம்",
            "category": "Food & Grocery", "subCategory": "Millets", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Cholam", "White Jowar Grain", "Jonnalu", "Jola", "Great Millet"],
            "aliases": ["Whole Sorghum Seeds", "Desi Shalu Jowar"],
            "brands": ["Tata Sampann", "Organic Tattva", "24 Mantra", "BB Royal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "millet_finger_ragi_whole",
            "name": "Whole Finger Millet / Ragi",
            "tamilName": "கேழ்வரகு முழு தானியம்",
            "category": "Food & Grocery", "subCategory": "Millets", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Kezhvaragu", "Ragi Seeds", "Ragulu", "Nachni Grains", "Mandua"],
            "aliases": ["Sprouting Ragi Seeds", "Desi Red Ragi Whole"],
            "brands": ["Tata Sampann", "Udhayam", "24 Mantra", "Naga", "Organic Tattva"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [1.0, 2.0, 5.0]
        },

        # --- DALS & PULSES EXPANSION ---
        {
            "id": "dal_toor_unpolished_desi",
            "name": "Desi Unpolished Toor Dal",
            "tamilName": "நாட்டுக் கைக்குத்தல் துவரம் பருப்பு",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Desi Tuvar Dal", "Unpolished Arhar Dal", "Hand Pounded Toor Dal", "Fatki Toor"],
            "aliases": ["Organic Toor Dal", "Non-oily Toor Dal"],
            "brands": ["Tata Sampann", "24 Mantra", "Organic Tattva", "Aashirvaad", "Natureland"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0, 2.0, 5.0]
        },
        {
            "id": "dal_toor_oily_vasad",
            "name": "Vasad Oily Toor Dal (Gujarat Special)",
            "tamilName": "குஜராத் வாசத் எண்ணெய் துவரம் பருப்பு",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Oily Tuvar Dal", "Telia Tuvar", "Vasad Tuver", "Castor Oiled Toor Dal"],
            "aliases": ["Preserved Oily Toor Dal", "Long Life Tuvar Dal"],
            "brands": ["Laxmi", "Vasadwala", "Fortune", "Chitale"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "dal_urad_split_black_chilka",
            "name": "Split Black Urad Dal with Husk",
            "tamilName": "உடைத்த கருப்பு உளுந்தம் பருப்பு",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Chilka Urad Dal", "Split Black Gram", "Kali Dal Split", "Karuppu Ulundhu Udachadhu"],
            "aliases": ["Black Dal for Dal Tadka", "High Fiber Urad"],
            "brands": ["Tata Sampann", "Fortune", "BB Royal", "Organic Tattva", "Udhayam"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "dal_urad_split_white_dhuli",
            "name": "Split White Urad Dal",
            "tamilName": "உடைத்த வெள்ளை உளுந்தம் பருப்பு",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["White Urad Split", "Dhuli Urad Dal", "Vellai Ulundhu Udachadhu"],
            "aliases": ["Idli Vada Split Urad", "Tempering Urad Dal"],
            "brands": ["Tata Sampann", "Udhayam", "Fortune", "BB Royal", "Naga"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0, 2.0, 5.0]
        },
        {
            "id": "dal_chana_roasted_pottukadalai",
            "name": "Roasted Gram / Daria Dal",
            "tamilName": "பொட்டுக்கடலை / வறுத்த கடலை",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Pottukadalai", "Roasted Bengal Gram", "Chana Daria", "Phutana Dal", "Hurigadale"],
            "aliases": ["Chutney Dal", "Roasted Chana Split for Chutney"],
            "brands": ["Udhayam", "Tata Sampann", "BB Royal", "Naga", "Double Horse"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.25, 0.5, 1.0, 2.0]
        },
        {
            "id": "pulse_horsegram_kollu",
            "name": "Horse Gram / Kollu Whole",
            "tamilName": "கொள்ளு முழு தானியம்",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Kollu", "Kulthi Dal", "Hurali", "Ulavalu", "Madras Horse Gram"],
            "aliases": ["Fat Burning Kollu Dal", "Weight Loss Horse Gram"],
            "brands": ["Udhayam", "Tata Sampann", "24 Mantra", "Organic Tattva", "BB Royal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "pulse_moth_beans_matki",
            "name": "Moth Beans / Matki Whole",
            "tamilName": "மட்கி / பனிப்பயறு",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Matki", "Moth Beans", "Turkish Gram", "Dew Bean", "Sprouting Matki"],
            "aliases": ["Misal Matki", "Sprouted Moth"],
            "brands": ["Tata Sampann", "BB Royal", "Chitale", "Fortune", "Organic Tattva"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0]
        },
        {
            "id": "pulse_lobia_white_cowpea",
            "name": "White Cowpea / Lobia (Black Eyed Peas)",
            "tamilName": "வெள்ளை காராமணி",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Safed Lobia", "Black Eyed Beans", "Vellai Karamani", "Alasande"],
            "aliases": ["Chawli White", "Black Eyed Susans"],
            "brands": ["Tata Sampann", "BB Royal", "Fortune", "Organic Tattva"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0]
        },
        {
            "id": "pulse_lobia_red_cowpea",
            "name": "Red Cowpea / Red Chawli",
            "tamilName": "சிவப்பு காராமணி",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Lal Lobia", "Red Karamani", "Lal Chawli", "Vanpayar"],
            "aliases": ["Kerala Vanpayar for Olan", "Red Cowpeas"],
            "brands": ["Double Horse", "Tata Sampann", "BB Royal", "Kitchen Treasures"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0]
        },
        {
            "id": "pulse_peas_dried_green",
            "name": "Dried Green Peas / Sukha Matar",
            "tamilName": "உலர்ந்த பச்சை பட்டாணி",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Dry Green Peas", "Hara Vatana", "Pachai Pattani", "Dry Ragda Peas"],
            "aliases": ["Street Chaat Green Peas", "Soaking Green Peas"],
            "brands": ["Tata Sampann", "BB Royal", "Fortune", "Udhayam"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0]
        },
        {
            "id": "pulse_peas_dried_white_vatana",
            "name": "Dried White Peas / Safed Vatana",
            "tamilName": "வெள்ளை பட்டாணி",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Safed Matar", "White Vatana", "Vellai Pattani", "Ragda Chaat Peas"],
            "aliases": ["Mumbai Ragda Pattani", "Dried Yellow Peas"],
            "brands": ["Tata Sampann", "BB Royal", "Fortune", "Udhayam"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0]
        },
        {
            "id": "pulse_mochai_field_beans",
            "name": "Dried Field Beans / Mochai",
            "tamilName": "மொச்சை பருப்பு / உலர் மொச்சை",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Mochai Kottai", "Val Dal", "Field Beans Dried", "Avarekalu Dried"],
            "aliases": ["Hyacinth Beans Dried", "South Indian Mochai"],
            "brands": ["Udhayam", "BB Royal", "Naga", "Double Horse"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0]
        },
        {
            "id": "pulse_chana_kala_desi",
            "name": "Small Desi Kala Chana (Brown Chickpeas)",
            "tamilName": "நாட்டு கருப்பு கொண்டைக்கடலை",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Desi Chana", "Black Bengal Gram", "Nattu Karuppu Sundal Kadalai"],
            "aliases": ["Navratri Kala Chana", "Sprouting Desi Chickpeas"],
            "brands": ["Tata Sampann", "Udhayam", "Organic Tattva", "Fortune"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "pulse_chana_kabuli_jumbo",
            "name": "Jumbo Dollar Kabuli Chana (White Chickpeas)",
            "tamilName": "பெரிய டாலர் வெள்ளை கொண்டைக்கடலை",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Dollar Chana", "Jumbo White Chana", "Bhatura Chole Chana", "Periya Vellai Kadalai"],
            "aliases": ["Pindi Chole Chickpeas", "Big Garbanzo Beans"],
            "brands": ["Tata Sampann", "Fortune", "BB Royal", "Udhayam"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "pulse_rajma_chitra",
            "name": "Rajma Chitra (Speckled Kidney Beans)",
            "tamilName": "சித்ரா ராஜ்மா பீன்ஸ்",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Chitra Rajma", "Kashmir Chitra Kidney Beans", "Spotted Rajma"],
            "aliases": ["Easy Cooking Rajma", "Pintado Rajma"],
            "brands": ["Tata Sampann", "Fortune", "BB Royal", "Organic Tattva"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "pulse_rajma_jammu_red",
            "name": "Jammu Red Small Rajma",
            "tamilName": "ஜம்மு சிவப்பு ராஜ்மா",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Small Red Rajma", "Kashmiri Red Kidney Beans", "Jammu Rajma"],
            "aliases": ["Authentic Jammu Rajma Chawal Beans"],
            "brands": ["Tata Sampann", "BB Royal", "Natureland", "Organic Tattva"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [0.5, 1.0]
        },
        {
            "id": "pulse_soya_chunks_mini",
            "name": "Mini Soya Chunks",
            "tamilName": "சிறிய சோயா சங்க்ஸ் / மீல்மேக்கர்",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 200.0,
            "commonNames": ["Nutrela Mini Chunks", "Meal Maker Small", "Bite Size Soy Chunks"],
            "aliases": ["Vegetarian High Protein Mini Chunks"],
            "brands": ["Nutrela", "Fortune", "Saffola", "BB Royal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [200.0, 500.0, 1000.0]
        },
        {
            "id": "pulse_soya_granules",
            "name": "Soya Granules / Minced Soy",
            "tamilName": "சோயா குருணை / வெஜ் கீமா",
            "category": "Food & Grocery", "subCategory": "Dals & Pulses", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 200.0,
            "commonNames": ["Nutrela Granules", "Soy Keema", "Textured Vegetable Protein Mince"],
            "aliases": ["Veg Keema Granules", "Bhurji Soy Granules"],
            "brands": ["Nutrela", "Fortune", "BB Royal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "dal", "customQuantities": [200.0, 500.0]
        },

        # --- FLOURS, SOOJI & NOODLES/PASTA ---
        {
            "id": "flour_sharbati_atta",
            "name": "MP Sharbati Whole Wheat Atta",
            "tamilName": "எம்பி ஷர்பதி முழு கோதுமை மாவு",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 5.0,
            "commonNames": ["Sharbati Wheat Flour", "Sehore Sharbati Atta", "Golden Wheat Flour"],
            "aliases": ["Sweet Sharbati Atta", "Rotis Soft Atta"],
            "brands": ["Aashirvaad Select", "Fortune", "Pillsbury", "Nature Fresh"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [1.0, 5.0, 10.0]
        },
        {
            "id": "flour_multigrain_atta",
            "name": "Multigrain High Fiber Atta",
            "tamilName": "மல்டிகிரைன் சத்து மாவு",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 5.0,
            "commonNames": ["Multigrain Wheat Flour", "6 Grain Atta", "Diabetic Friendly Atta"],
            "aliases": ["Aashirvaad Multigrain", "Soya Chana Oat Wheat Atta"],
            "brands": ["Aashirvaad", "Pillsbury", "Fortune", "Organic Tattva"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [1.0, 5.0, 10.0]
        },
        {
            "id": "flour_sattu_chana",
            "name": "Roasted Chana Sattu Flour",
            "tamilName": "வறுத்த சத்து மாவு / சத்து மாவு",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 500.0,
            "commonNames": ["Chana Sattu", "Bihari Sattu", "Roasted Gram Flour Energy Drink", "Barley Chana Sattu"],
            "aliases": ["Sattu Drink Powder", "Desi Protein Shake Sattu"],
            "brands": ["Rajdhani", "Patanjali", "BB Royal", "Organic Tattva", "Natureland"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [500.0, 1000.0]
        },
        {
            "id": "flour_idiyappam_steamed",
            "name": "Steamed Rice Idiyappam Flour",
            "tamilName": "இடியாப்பம் அவித்த பச்சரிசி மாவு",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["String Hopper Flour", "Sevai Maavu", "Noolputtu Podi", "Steamed Pathiri Podi"],
            "aliases": ["Soft Idiyappam Flour", "Double Horse Idiyappam"],
            "brands": ["Double Horse", "Nirapara", "Brahmins", "Eastern", "Udhayam", "Anil"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "flour_puttu_chemba_red",
            "name": "Chemba Red Rice Puttu Podi",
            "tamilName": "செம்பா சிகப்பரிசி புட்டுப் பொடி",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Red Puttu Flour", "Chemba Puttu Podi", "Kerala Red Rice Puttu"],
            "aliases": ["Double Horse Chemba Puttu Podi", "Diet Red Puttu"],
            "brands": ["Double Horse", "Nirapara", "Kitchen Treasures", "Brahmins", "Eastern"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0]
        },
        {
            "id": "flour_puttu_ragi",
            "name": "Ragi Puttu Podi / Finger Millet Puttu Flour",
            "tamilName": "கேழ்வரகு புட்டுப் பொடி",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Ragi Puttu Flour", "Kezhvaragu Puttu Maavu"],
            "aliases": ["Nachni Puttu Podi", "Healthy Calcium Puttu"],
            "brands": ["Double Horse", "Eastern", "Brahmins", "Nirapara", "Anil"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0]
        },
        {
            "id": "flour_ragi_malt_sprouted",
            "name": "Sprouted Ragi Flour / Ragi Malt",
            "tamilName": "முளைகட்டிய கேழ்வரகு மாவு / ராகி மால்ட்",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 500.0,
            "commonNames": ["Sprouted Nachni Satva", "Baby Ragi Porridge Flour", "Ragi Malt Drink Mix"],
            "aliases": ["Mulaikattiya Kezhvaragu", "Organic Sprouted Ragi Powder"],
            "brands": ["Manna", "Slurrp Farm", "24 Mantra", "Organic Tattva", "Patanjali"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [250.0, 500.0, 1000.0]
        },
        {
            "id": "flour_makki_corn_yellow",
            "name": "Yellow Maize Flour / Makki Ka Atta",
            "tamilName": "மக்காச்சோள மாவு",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Makki Atta", "Yellow Cornmeal", "Makka Flour for Roti", "Sarson Roti Atta"],
            "aliases": ["Corn Flour for Roti", "Punjabi Makki Atta"],
            "brands": ["Fortune", "Rajdhani", "BB Royal", "Natureland"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [1.0, 2.0]
        },
        {
            "id": "flour_singhare_water_chestnut",
            "name": "Water Chestnut Flour / Singhare Ka Atta",
            "tamilName": "சிங்காரா மாவு (நோன்பு மாவு)",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 500.0,
            "commonNames": ["Singhara Atta", "Vrat Ka Atta", "Water Chestnut Starch Flour"],
            "aliases": ["Fasting Flour", "Navratri Singhara Flour"],
            "brands": ["Fortune", "Rajdhani", "BB Royal", "Patanjali"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [250.0, 500.0, 1000.0]
        },
        {
            "id": "flour_kuttu_buckwheat",
            "name": "Buckwheat Flour / Kuttu Ka Atta",
            "tamilName": "பக்வீட் மாவு / குட்டு மாவு",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 500.0,
            "commonNames": ["Kuttu Flour", "Buckwheat Groats Flour", "Vrat Kuttu Puri Atta"],
            "aliases": ["Fasting Buckwheat", "Gluten-free Kuttu"],
            "brands": ["Fortune", "Rajdhani", "BB Royal", "Natureland"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [250.0, 500.0, 1000.0]
        },
        {
            "id": "flour_rajgira_amaranth",
            "name": "Amaranth Flour / Rajgira Ka Atta",
            "tamilName": "ராஜ்ஜிரா மாவு / தண்டுக்கீரை விதை மாவு",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 500.0,
            "commonNames": ["Rajgira Atta", "Chaulai Ka Atta", "Amaranth Seed Flour"],
            "aliases": ["Ramdana Flour", "High Protein Vrat Atta"],
            "brands": ["Fortune", "Rajdhani", "BB Royal", "Natureland"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [250.0, 500.0]
        },
        {
            "id": "rava_bansi_kesari",
            "name": "Bansi Kesari Rava (Hard Durum Wheat Semolina)",
            "tamilName": "பன்சி கேசரி ரவை",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Bansi Rava", "Durum Sooji", "Yellow Bansi Semolina", "Karanji Rava"],
            "aliases": ["Kesari Bath Rava", "Coarse Bansi Suji"],
            "brands": ["Naga", "Fortune", "Udhayam", "BB Royal", "MTR"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "rava_chiroti_fine_maida_suji",
            "name": "Chiroti Fine Rava",
            "tamilName": "சிரோட்டி மெல்லிய ரவை",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Chiroti Sooji", "Fine Semolina", "Sweet Making Rava", "Halwa Fine Suji"],
            "aliases": ["Pheni Rava", "Ultra Fine Sooji"],
            "brands": ["Naga", "Fortune", "BB Royal", "Chitale"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0]
        },
        {
            "id": "rava_idli_rice_cream",
            "name": "Rice Idli Rava",
            "tamilName": "இட்லி அரிசி ரவை",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Cream of Rice", "Arisi Rava for Idli", "Andhra Idli Rava"],
            "aliases": ["Pothana Idli Rava", "Boiled Rice Rava"],
            "brands": ["Udhayam", "Priya", "Naga", "Double Horse", "BB Royal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "pasta_macaroni_durum_wheat",
            "name": "100% Durum Wheat Macaroni Elbow Pasta",
            "tamilName": "கோதுமை மேக்ரோனி பாஸ்தா",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 500.0,
            "commonNames": ["Elbow Macaroni", "Indian Macaroni Pasta", "Suji Macaroni"],
            "aliases": ["Desi Style Macaroni", "Cheese Macaroni"],
            "brands": ["Bambino", "Weikfield", "Maggi", "Barilla", "Disano", "BB Royal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [400.0, 500.0, 1000.0]
        },
        {
            "id": "pasta_penne_rigate_durum",
            "name": "Durum Wheat Penne Rigate Pasta",
            "tamilName": "பென்னே பாஸ்தா",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 500.0,
            "commonNames": ["Penne Pasta", "Tube Pasta", "Italian Penne Rigate"],
            "aliases": ["Red Sauce Penne", "Borges Penne Pasta"],
            "brands": ["Borges", "Barilla", "Bambino", "Disano", "Del Monte"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [500.0, 1000.0]
        },
        {
            "id": "pasta_fusilli_spirals",
            "name": "Durum Wheat Fusilli Spiral Pasta",
            "tamilName": "சுருள் பியூசில்லி பாஸ்தா",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 500.0,
            "commonNames": ["Spiral Pasta", "Fusilli Screws Pasta", "Twist Pasta"],
            "aliases": ["Salad Spiral Pasta", "Borges Fusilli"],
            "brands": ["Borges", "Barilla", "Bambino", "Disano"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [500.0, 1000.0]
        },
        {
            "id": "noodles_hakka_veg",
            "name": "Plain Hakka Veg Chowmein Noodles",
            "tamilName": "ஹக்கா வெஜ் நூடுல்ஸ்",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 300.0,
            "commonNames": ["Chinese Hakka Noodles", "Ching's Hakka Noodles", "Chowmein Stir Fry Noodles"],
            "aliases": ["Street Style Chowmein", "Desi Chinese Noodles"],
            "brands": ["Ching's Secret", "Weikfield", "Smith & Jones", "Bambino"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [150.0, 300.0, 600.0]
        },
        {
            "id": "vermicelli_ragi_finger_millet",
            "name": "Ragi Vermicelli / Sevai",
            "tamilName": "கேழ்வரகு சேமியா",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 200.0,
            "commonNames": ["Ragi Semiya", "Nachni Vermicelli", "Finger Millet Sevai"],
            "aliases": ["Anil Ragi Semiya", "Healthy Breakfast Sevai"],
            "brands": ["Anil", "MTR", "Aachi", "Double Horse", "Naga"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [180.0, 200.0, 400.0, 500.0]
        },
        {
            "id": "vermicelli_wheat_semiya_roasted",
            "name": "Roasted Wheat Vermicelli / Semiya",
            "tamilName": "வறுத்த கோதுமை சேமியா",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 400.0,
            "commonNames": ["Roasted Semiya", "Bhuni Seviyan", "Payasam Semiya Roasted", "Upma Vermicelli"],
            "aliases": ["Bambino Roasted Vermicelli", "MTR Roasted Seviyan"],
            "brands": ["Bambino", "MTR", "Anil", "Naga", "Aashirvaad"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [200.0, 400.0, 500.0, 1000.0]
        },
        {
            "id": "sabudana_nylon_small",
            "name": "Nylon Small Sago / Sabudana",
            "tamilName": "நைலான் ஜவ்வரிசி (சிறியது)",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Nylon Javvarisi", "Small Sago Pearls", "Payasam Javvarisi"],
            "aliases": ["Kheer Sago", "Fine Sabudana"],
            "brands": ["Fortune", "Tata Sampann", "BB Royal", "Udhayam"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0]
        },
        {
            "id": "sabudana_big_vada",
            "name": "Large Tapioca Sago for Sabudana Vada",
            "tamilName": "பெரிய வடை ஜவ்வரிசி",
            "category": "Food & Grocery", "subCategory": "Flours & Grains", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 0.5,
            "commonNames": ["Mota Sabudana", "Periya Javvarisi", "Khichdi Sabudana", "Big Sago Pearls"],
            "aliases": ["Salem Sago Mota", "Fasting Tapioca Pearls"],
            "brands": ["Fortune", "Tata Sampann", "BB Royal", "Chitale"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "grains", "customQuantities": [0.5, 1.0, 2.0]
        },

        # --- BAKING & COOKING INGREDIENTS ---
        {
            "id": "baking_active_dry_yeast",
            "name": "Active Dry Yeast Granules",
            "tamilName": "செயல்மிகு உலர் ஈஸ்ட்",
            "category": "Food & Grocery", "subCategory": "Baking Ingredients", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Refrigerator", "minimumQuantity": 50.0,
            "commonNames": ["Dry Yeast for Bread", "Instant Baker's Yeast", "Khamir"],
            "aliases": ["Bread Making Yeast", "Active Yeast Tin"],
            "brands": ["Weikfield", "Urban Platter", "Puratos", "Gloripan"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "baking", "customQuantities": [50.0, 100.0, 500.0]
        },
        {
            "id": "baking_cocoa_powder_unsweetened",
            "name": "Unsweetened Dutch Process Cocoa Powder",
            "tamilName": "இனிப்பற்ற தூய கொக்கோ பவுடர்",
            "category": "Food & Grocery", "subCategory": "Baking Ingredients", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 100.0,
            "commonNames": ["Pure Cocoa Powder", "Baking Chocolate Powder", "Dark Cocoa Powder"],
            "aliases": ["Cadbury Cocoa Powder", "Hershey's Unsweetened Cocoa"],
            "brands": ["Cadbury", "Hershey's", "Weikfield", "Urban Platter", "Van Houten"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "baking", "customQuantities": [100.0, 150.0, 250.0]
        },
        {
            "id": "baking_vanilla_extract_essence",
            "name": "Vanilla Essence Extract Liquid",
            "tamilName": "வெண்ணிலா எசென்ஸ் வாசனை திரவம்",
            "category": "Food & Grocery", "subCategory": "Baking Ingredients", "productType": "staple",
            "defaultUnit": "ml", "soldBy": "bottle", "storageLocation": "Pantry Shelf", "minimumQuantity": 20.0,
            "commonNames": ["Vanilla Flavor Liquid", "Cake Vanilla Essence"],
            "aliases": ["Vanilla Aroma Drops", "Pure Vanilla Extract"],
            "brands": ["Weikfield", "Eagle", "Urban Platter", "Ossoro"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "baking", "customQuantities": [20.0, 50.0, 100.0]
        },
        {
            "id": "baking_corn_flour_starch",
            "name": "Edible Corn Flour / Cornstarch",
            "tamilName": "சோள மாவு (கார்ன் ஃப்ளார்)",
            "category": "Food & Grocery", "subCategory": "Baking Ingredients", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 100.0,
            "commonNames": ["Cornstarch", "White Maize Starch", "Soup Thickening Powder"],
            "aliases": ["Makka Starch", "Weikfield Cornflour"],
            "brands": ["Weikfield", "Brown & Polson", "Blue Bird", "BB Royal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "baking", "customQuantities": [100.0, 500.0, 1000.0]
        },
        {
            "id": "baking_custard_powder_vanilla",
            "name": "Vanilla Custard Powder",
            "tamilName": "வெண்ணிலா கஸ்டர்ட் பவுடர்",
            "category": "Food & Grocery", "subCategory": "Baking Ingredients", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 100.0,
            "commonNames": ["Fruit Salad Custard", "Vanilla Pudding Powder", "Pudding Custard"],
            "aliases": ["Brown & Polson Custard Powder", "Weikfield Custard"],
            "brands": ["Brown & Polson", "Weikfield", "Blue Bird"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "baking", "customQuantities": [100.0, 250.0, 500.0]
        },
        {
            "id": "baking_agar_agar_china_grass",
            "name": "China Grass / Agar Agar Strips & Powder",
            "tamilName": "கடற்பாசி / சைனா கிராஸ்",
            "category": "Food & Grocery", "subCategory": "Baking Ingredients", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 25.0,
            "commonNames": ["Kadal Paasi", "Vegetarian Gelatin", "Agar Agar Flakes"],
            "aliases": ["Jelly Grass", "Plant Based Gelling Agent"],
            "brands": ["Urban Platter", "Meron", "Weikfield", "Blue Bird"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "baking", "customQuantities": [25.0, 50.0, 100.0]
        },
        {
            "id": "baking_citric_acid_crystals",
            "name": "Citric Acid Crystals / Tatri",
            "tamilName": "எலுமிச்சை உப்பு / சிட்ரிக் அமிலம்",
            "category": "Food & Grocery", "subCategory": "Baking Ingredients", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 50.0,
            "commonNames": ["Nimbu Ka Sat", "Lemon Salt Crystals", "Elumichai Uppu", "Sour Salt"],
            "aliases": ["Preservative Citric Acid", "Dhokla Tartaric Acid"],
            "brands": ["Urban Platter", "Weikfield", "Catch", "BB Royal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "baking", "customQuantities": [50.0, 100.0, 250.0]
        },
    ]
    return items

