# Expand Oils, Fats, Spices, Masalas, Salts, Sweeteners, Pickles, Sauces, Chutneys, Vathals
# Adds ~450 highly curated Indian products with authentic Tamil names, units, and brands.

def get_oils_spices_condiments_expansion():
    items = [
        # --- OILS & FATS ---
        {
            "id": "oil_gingelly_wood_pressed",
            "name": "Wood Pressed Chekku Gingelly / Sesame Oil",
            "tamilName": "மரச்செக்கு நல்லெண்ணெய்",
            "category": "Oils & Fats", "subCategory": "Cooking Oils", "productType": "staple",
            "defaultUnit": "L", "soldBy": "volume", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 1.0,
            "commonNames": ["Nallennai", "Til Ka Tel", "Kachi Ghani Sesame Oil", "Chekku Nallennai"],
            "aliases": ["Cold Pressed Gingelly Oil", "Pure Sesame Cooking Oil"],
            "brands": ["Idhayam", "Anjali", "VVD", "Gramiyum", "Puvi", "Organic Tattva"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "oil", "customQuantities": [0.5, 1.0, 2.0, 5.0]
        },
        {
            "id": "oil_groundnut_cold_pressed",
            "name": "Cold Pressed Chekku Groundnut / Peanut Oil",
            "tamilName": "மரச்செக்கு கடலை எண்ணெய்",
            "category": "Oils & Fats", "subCategory": "Cooking Oils", "productType": "staple",
            "defaultUnit": "L", "soldBy": "volume", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 1.0,
            "commonNames": ["Kadalai Ennai", "Mungfali Ka Tel", "Kachi Ghani Peanut Oil", "Chekku Kadalai Ennai"],
            "aliases": ["Wood Pressed Peanut Oil", "Filtration Groundnut Oil"],
            "brands": ["Idhayam Mantra", "Fortune", "Puvi", "Gramiyum", "Dhara", "Gulab"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "oil", "customQuantities": [0.5, 1.0, 2.0, 5.0]
        },
        {
            "id": "oil_coconut_cold_pressed_cooking",
            "name": "Cold Pressed Edible Coconut Cooking Oil",
            "tamilName": "மரச்செக்கு சமையல் தேங்காய் எண்ணெய்",
            "category": "Oils & Fats", "subCategory": "Cooking Oils", "productType": "staple",
            "defaultUnit": "L", "soldBy": "volume", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 1.0,
            "commonNames": ["Thengai Ennai", "Nariyal Tel Cooking", "Kera Cooking Oil", "Kerala Coconut Oil"],
            "aliases": ["Wood Pressed Coconut Oil", "Pure Desi Coconut Oil"],
            "brands": ["KLF Coconad", "Double Horse", "Parachute Edible", "VVD", "Coco Soul", "Aashirvaad Svasti"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "oil", "customQuantities": [0.5, 1.0, 2.0, 5.0]
        },
        {
            "id": "oil_mustard_kachi_ghani",
            "name": "Kachi Ghani Cold Pressed Mustard Oil",
            "tamilName": "மரச்செக்கு கடுகு எண்ணெய்",
            "category": "Oils & Fats", "subCategory": "Cooking Oils", "productType": "staple",
            "defaultUnit": "L", "soldBy": "volume", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 1.0,
            "commonNames": ["Sarson Ka Tel", "Kadugu Ennai", "Pungent Mustard Oil", "Raw Mustard Oil"],
            "aliases": ["Kachi Ghani Sarson", "Mustard Oil for Pickles"],
            "brands": ["Fortune", "Engine", "Dhara", "Bail Kolhu", "Patanjali", "Emami Healthy & Tasty"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "oil", "customQuantities": [0.5, 1.0, 2.0, 5.0]
        },
        {
            "id": "oil_sunflower_refined",
            "name": "Refined Sunflower Cooking Oil",
            "tamilName": "சூரியகாந்தி சுத்திகரிக்கப்பட்ட சமையல் எண்ணெய்",
            "category": "Oils & Fats", "subCategory": "Cooking Oils", "productType": "staple",
            "defaultUnit": "L", "soldBy": "volume", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 1.0,
            "commonNames": ["Sunflower Oil Pouch", "Surajmukhi Tel", "Light Cooking Oil"],
            "aliases": ["Fortune Sunflower Oil", "Gold Winner Sunflower Oil", "Sunpure Oil"],
            "brands": ["Fortune", "Gold Winner", "Sunpure", "Gemini", "Freedom", "Saffola"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "oil", "customQuantities": [1.0, 2.0, 5.0, 15.0]
        },
        {
            "id": "oil_ricebran_physically_refined",
            "name": "Physically Refined Rice Bran Oil",
            "tamilName": "தவிட்டு எண்ணெய் (ரைஸ்பிரான் ஆயில்)",
            "category": "Oils & Fats", "subCategory": "Cooking Oils", "productType": "staple",
            "defaultUnit": "L", "soldBy": "volume", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 1.0,
            "commonNames": ["Rice Bran Oil", "Heart Friendly Rice Bran", "High Oryzanol Oil"],
            "aliases": ["Fortune Rice Bran", "Saffola Gold Blended Rice Bran"],
            "brands": ["Fortune", "Saffola", "Emami", "Dhara", "Freedom"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "oil", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "oil_olive_extra_virgin",
            "name": "Extra Virgin Cold Pressed Olive Oil",
            "tamilName": "எக்ஸ்ட்ரா விர்ஜின் ஆலிவ் எண்ணெய்",
            "category": "Oils & Fats", "subCategory": "Cooking Oils", "productType": "staple",
            "defaultUnit": "L", "soldBy": "volume", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 0.5,
            "commonNames": ["Extra Virgin Olive Oil", "Salad Dressing Olive Oil", "EVOO Glass Bottle"],
            "aliases": ["Borges Extra Virgin Olive Oil", "Figaro Olive Oil", "Disano EVOO"],
            "brands": ["Borges", "Figaro", "Disano", "Del Monte", "Bertolli"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "oil", "customQuantities": [0.25, 0.5, 1.0, 2.0, 5.0]
        },
        {
            "id": "oil_olive_pomace",
            "name": "Olive Pomace Oil for Indian Cooking",
            "tamilName": "பொமேஸ் ஆலிவ் எண்ணெய் (இந்திய சமையலுக்கு)",
            "category": "Oils & Fats", "subCategory": "Cooking Oils", "productType": "staple",
            "defaultUnit": "L", "soldBy": "volume", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 1.0,
            "commonNames": ["Pomace Olive Oil", "High Smoke Point Olive Oil", "Cooking Olive Oil"],
            "aliases": ["Borges Pomace Olive Oil", "Disano Pomace"],
            "brands": ["Borges", "Figaro", "Disano", "Del Monte"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "oil", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "oil_deepam_pooja_blend",
            "name": "Panchadeepam Pooja Lamp Oil",
            "tamilName": "பஞ்சதீபம் பூஜை விளக்கெண்ணெய் / தீப எண்ணெய்",
            "category": "Home Utility & Pooja", "subCategory": "Pooja Items", "productType": "household_utility",
            "defaultUnit": "L", "soldBy": "volume", "storageLocation": "Utility Room", "minimumQuantity": 1.0,
            "commonNames": ["Deepam Oil", "Pooja Ennai", "5 Oil Lamp Blend", "Vilakku Ennai"],
            "aliases": ["Kalyani Pooja Oil", "Gopuram Deepam Oil"],
            "brands": ["Kalyani", "Gopuram", "Cycle", "Idhayam Deepam", "Anjali"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "utility", "customQuantities": [0.5, 1.0, 2.0, 5.0]
        },
        {
            "id": "oil_castor_pure_vilakkenai",
            "name": "Pure Castor Oil / Vilakkenai",
            "tamilName": "சுத்தமான ஆமணக்கு விளக்கெண்ணெய்",
            "category": "Oils & Fats", "subCategory": "Cooking Oils", "productType": "staple",
            "defaultUnit": "ml", "soldBy": "bottle", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 200.0,
            "commonNames": ["Amanakku Ennai", "Castor Oil", "Arandi Ka Tel", "Cooling Castor Oil"],
            "aliases": ["Grain Preserving Castor Oil", "Pure Castor Cold Pressed"],
            "brands": ["Puvi", "Gramiyum", "Organic Tattva", "VVD", "Urban Platter"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "oil", "customQuantities": [100.0, 200.0, 500.0]
        },
        {
            "id": "ghee_desi_cow_pure",
            "name": "Pure Desi Cow Ghee (Danedar)",
            "tamilName": "தூய நாட்டுப் பசு நெய்",
            "category": "Oils & Fats", "subCategory": "Cooking Oils", "productType": "staple",
            "defaultUnit": "ml", "soldBy": "volume", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 500.0,
            "commonNames": ["Pasu Nei", "Cow Ghee Jar", "Danedar Cow Ghee", "Desi Ghee Tin"],
            "aliases": ["Amul Cow Ghee", "Aashirvaad Svasti Cow Ghee", "Gowardhan Ghee"],
            "brands": ["Amul", "Aashirvaad Svasti", "Gowardhan", "Nandini", "Patanjali", "Mother Dairy"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "oil", "customQuantities": [200.0, 500.0, 1000.0, 5000.0]
        },
        {
            "id": "ghee_a2_gir_cow_bilona",
            "name": "A2 Gir Cow Vedic Bilona Ghee",
            "tamilName": "A2 கிர் பசு பாரம்பரிய மத்து கடைந்த நெய்",
            "category": "Oils & Fats", "subCategory": "Cooking Oils", "productType": "staple",
            "defaultUnit": "ml", "soldBy": "bottle", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 500.0,
            "commonNames": ["A2 Ghee", "Bilona Method Cow Ghee", "Grass Fed Desi Ghee", "Curd Churned Ghee"],
            "aliases": ["Kapiva A2 Ghee", "Anveshan A2 Ghee", "Two Brothers A2 Ghee"],
            "brands": ["Kapiva", "Anveshan", "Two Brothers", "Organic India", "Gir Organic"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "oil", "customQuantities": [250.0, 500.0, 1000.0]
        },
        {
            "id": "fat_vanaspati_dalda",
            "name": "Hydrogenated Vegetable Cooking Fat / Vanaspati",
            "tamilName": "வனஸ்பதி டால்டா",
            "category": "Oils & Fats", "subCategory": "Cooking Oils", "productType": "staple",
            "defaultUnit": "L", "soldBy": "volume", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 1.0,
            "commonNames": ["Dalda Vanaspati", "Vegetable Ghee", "Vanaspati Pouch", "Bhatura Frying Fat"],
            "aliases": ["Baking Vanaspati", "Dalda Hydrogenated Fat"],
            "brands": ["Dalda", "Rath", "Panghat", "Gagan"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "oil", "customQuantities": [0.5, 1.0, 5.0]
        },

        # --- WHOLE SPICES & HERBS ---
        {
            "id": "spice_cardamom_green_bold_8mm",
            "name": "Green Cardamom Extra Bold 8mm",
            "tamilName": "பச்சை ஏலக்காய் 8 மிமீ",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 50.0,
            "commonNames": ["Elaichi Bold", "Pachai Elakkai", "Chhoti Elaichi", "Malabar Cardamom"],
            "aliases": ["Royal Green Cardamom", "Jumbo Elaichi"],
            "brands": ["Everest", "Catch", "Tata Sampann", "Eastern", "Aachi"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [25.0, 50.0, 100.0, 250.0]
        },
        {
            "id": "spice_black_cardamom_badi_elaichi",
            "name": "Black Cardamom / Badi Elaichi",
            "tamilName": "கருப்பு ஏலக்காய்",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 50.0,
            "commonNames": ["Moti Elaichi", "Badi Elaichi", "Smoky Black Cardamom", "Biryani Badi Elaichi"],
            "aliases": ["Greater Cardamom", "Karuppu Elakkai"],
            "brands": ["Everest", "Catch", "Tata Sampann", "MDH"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0]
        },
        {
            "id": "spice_cloves_laung_lavangam",
            "name": "Whole Cloves / Lavangam",
            "tamilName": "கிராம்பு / லவங்கம்",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 50.0,
            "commonNames": ["Laung", "Grambu", "Lavang", "Zanzibar Cloves", "Handpicked Cloves"],
            "aliases": ["Aromatic Head Cloves", "Whole Lavangam"],
            "brands": ["Everest", "Catch", "Tata Sampann", "Aachi", "Eastern"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0, 250.0]
        },
        {
            "id": "spice_cinnamon_ceylon_true",
            "name": "Ceylon True Cinnamon Quills",
            "tamilName": "இலங்கை உண்மையான சுருள் பட்டை",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 50.0,
            "commonNames": ["Sri Lankan Cinnamon", "Curled Dalchini Quills", "Low Coumarin Cinnamon", "Surul Pattai"],
            "aliases": ["True Cinnamon Sticks", "Medicinal Ceylon Cinnamon"],
            "brands": ["Urban Platter", "Organic India", "Keya", "Tata Sampann"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0]
        },
        {
            "id": "spice_cinnamon_cassia_bark",
            "name": "Cassia Cinnamon Flat Bark / Dalchini",
            "tamilName": "மரப்பட்டை / தால்சினி",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 50.0,
            "commonNames": ["Dalchini Flat Bark", "Pattai", "Biryani Cinnamon", "Chinese Cassia"],
            "aliases": ["Curry Cinnamon Bark", "Biryani Pattai"],
            "brands": ["Everest", "Catch", "Aachi", "Tata Sampann", "Eastern"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0, 250.0]
        },
        {
            "id": "spice_pepper_tellicherry_garbled",
            "name": "Tellicherry Garbled Extra Bold Black Pepper",
            "tamilName": "தலச்சேரி தடித்த கருமிளகு",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["TGEB Black Pepper", "Malabar Garbled Pepper", "Karuppu Milagu", "Kali Mirch Whole"],
            "aliases": ["Export Quality Tellicherry Pepper", "Bold Peppercorns"],
            "brands": ["Tata Sampann", "Catch", "Eastern", "Everest", "Keya"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0, 250.0, 500.0]
        },
        {
            "id": "spice_pepper_white_whole",
            "name": "Whole White Peppercorns / Safed Mirch",
            "tamilName": "வெள்ளை மிளகு",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 50.0,
            "commonNames": ["Safed Mirch", "White Pepper Whole", "Vellai Milagu", "Dakhni Mirch"],
            "aliases": ["Dehusked Pepper", "Chinese Soup White Pepper"],
            "brands": ["Catch", "Everest", "Keya", "Urban Platter"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0]
        },
        {
            "id": "spice_star_anise_chakri_phool",
            "name": "Whole Star Anise / Thakkolam",
            "tamilName": "அன்னாசிப் பூ / தக்கோலம்",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 50.0,
            "commonNames": ["Chakra Phool", "Star Aniseed", "Biryani Star Flower", "Badiyan Ka Phool"],
            "aliases": ["Anasipoo", "Chinese Star Anise"],
            "brands": ["Catch", "Everest", "Tata Sampann", "Aachi", "Eastern"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0]
        },
        {
            "id": "spice_mace_javitri_flower",
            "name": "Whole Mace Flower / Javitri",
            "tamilName": "ஜாதிபத்திரி மலர்",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 25.0,
            "commonNames": ["Javitri Blades", "Mace Aril", "Jadhipathiri", "Biryani Mace"],
            "aliases": ["Nutmeg Outer Flower", "Golden Mace Blades"],
            "brands": ["Catch", "Everest", "Tata Sampann", "Aachi"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [25.0, 50.0, 100.0]
        },
        {
            "id": "spice_nutmeg_jaiphal_whole",
            "name": "Whole Nutmeg Kernel / Jaiphal",
            "tamilName": "முழு ஜாதிக்காய்",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 50.0,
            "commonNames": ["Jaiphal Seed", "Jadhikkai Whole", "Nutmeg Shell-free"],
            "aliases": ["Ayurvedic Jaiphal", "Sweet Spice Nutmeg"],
            "brands": ["Everest", "Catch", "Tata Sampann", "Aachi"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0]
        },
        {
            "id": "spice_stone_flower_kalpasi",
            "name": "Black Stone Flower / Kalpasi",
            "tamilName": "கல்பாசி (கருப்புக் கல் பாசி)",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 25.0,
            "commonNames": ["Dagad Phool", "Dagar Phool", "Lichen Spice", "Chettinad Kalpasi", "Pathar Ke Phool"],
            "aliases": ["Biryani Kalpasi", "Chettinad Special Lichen"],
            "brands": ["Aachi", "Tata Sampann", "Eastern", "Everest"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [25.0, 50.0, 100.0]
        },
        {
            "id": "spice_marathi_moggu_kapok",
            "name": "Marathi Moggu / Kapok Buds",
            "tamilName": "மராட்டி மொக்கு",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 25.0,
            "commonNames": ["Kapok Buds", "Bisi Bele Bath Moggu", "Chettinad Moggu", "Karanataka Moggu"],
            "aliases": ["Indian Caper Buds", "Marathi Mokku"],
            "brands": ["Aachi", "Tata Sampann", "Eastern", "MTR"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [25.0, 50.0]
        },
        {
            "id": "spice_chilli_byadgi_whole",
            "name": "Byadgi Karnataka Wrinkled Red Chillies",
            "tamilName": "பியாடகி சுருக்கமான மிளகாய் வற்றல்",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 250.0,
            "commonNames": ["Byadgi Mirch", "Deep Red Low Pungency Chilli", "Kaddi Chilli", "Wrinkled Red Chillies"],
            "aliases": ["Natural Red Colour Chilli", "Sambar Byadgi Milagai"],
            "brands": ["Tata Sampann", "Catch", "MTR", "Aachi", "Everest"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [100.0, 250.0, 500.0]
        },
        {
            "id": "spice_chilli_guntur_s4_whole",
            "name": "Guntur Sannam S4 Spicy Red Chillies",
            "tamilName": "குண்டூர் சன்னம் கார மிளகாய் வற்றல்",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 250.0,
            "commonNames": ["Guntur Mirchi", "Hot Red Chilli Whole", "Andhra Teja Chilli", "Needa Milagai"],
            "aliases": ["Super Spicy Andhra Chillies", "Guntur S4 Red Chilli"],
            "brands": ["Tata Sampann", "Everest", "Aachi", "Priya", "Catch"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [100.0, 250.0, 500.0, 1000.0]
        },
        {
            "id": "spice_chilli_salem_gundu_round",
            "name": "Salem Round Gundu Red Chillies",
            "tamilName": "சேலம் குண்டு மிளகாய் வற்றல்",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 200.0,
            "commonNames": ["Gundu Milagai", "Round Dried Chilli", "Ramanathapuram Mundu Chilli", "Chettinad Gundu Chilli"],
            "aliases": ["Sambar Gundu Milagai", "Thalippu Gundu Chilli"],
            "brands": ["Udhayam", "Aachi", "BB Royal", "Double Horse"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [100.0, 200.0, 500.0]
        },
        {
            "id": "spice_chilli_kashmiri_whole",
            "name": "Whole Dried Kashmiri Red Chillies",
            "tamilName": "காஷ்மீரி மிளகாய் வற்றல்",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Pantry Shelf", "minimumQuantity": 100.0,
            "commonNames": ["Kashmiri Mirch Sabut", "Mild Bright Red Chilli", "Curry Color Chilli Whole"],
            "aliases": ["Kashmiri Dried Peppers", "Zero Pungency Red Chilli"],
            "brands": ["Catch", "Everest", "Tata Sampann", "Urban Platter"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [100.0, 250.0]
        },
        {
            "id": "spice_saffron_kashmiri_kesar",
            "name": "Pure Kashmiri Mongra Saffron / Kesar",
            "tamilName": "தூய காஷ்மீர் குங்குமப்பூ",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Kashmiri Kesar", "Kumkumapoo", "Mongra Saffron Threads", "Zafran"],
            "aliases": ["Grade A1 Saffron", "Baby Food Saffron", "Biryani Saffron"],
            "brands": ["Baby Brand", "Lion", "Keya", "Urban Platter", "Organic India"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [0.5, 1.0, 2.0, 5.0]
        },
        {
            "id": "spice_kasuri_methi_leaves",
            "name": "Dried Fenugreek Leaves / Kasuri Methi",
            "tamilName": "கஸ்தூரி மேத்தி (உலர்ந்த வெந்தயக் கீரை)",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 50.0,
            "commonNames": ["Kasuri Methi", "Dried Methi Leaves", "Aromatic Fenugreek Herb", "Nagauri Methi"],
            "aliases": ["Mughlai Gravy Kasuri Methi", "Butter Chicken Herb"],
            "brands": ["Everest", "Catch", "MDH", "Tata Sampann", "Keya"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [25.0, 50.0, 100.0]
        },
        {
            "id": "spice_hing_rock_katti_crystal",
            "name": "Compounded Solid Rock Crystal Hing / Perungayam",
            "tamilName": "கட்டிப் பெருங்காயம்",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 50.0,
            "commonNames": ["Katti Perungayam", "Solid Hing Cake", "Compounded Asafoetida Lump"],
            "aliases": ["Traditional Sambar Katti Hing", "L.G. Katti Perungayam"],
            "brands": ["LG", "SS Pandian", "Patanjali", "Aachi"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0]
        },
        {
            "id": "spice_panch_phoron_bengal_blend",
            "name": "Panch Phoron Whole 5-Spice Blend (Bengal)",
            "tamilName": "பாஞ்ச் போரோன் வங்காள ஐந்து மசாலா கலவை",
            "category": "Spices & Seasonings", "subCategory": "Whole Spices", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Panch Phoran", "Bengali 5 Spices", "Five Seeds Tempering Blend"],
            "aliases": ["Cumin Fennel Mustard Fenugreek Nigella Mix", "Dheki Panch Phoron"],
            "brands": ["Catch", "Tata Sampann", "Urban Platter", "BB Royal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [100.0, 200.0]
        },

        # --- MASALA POWDERS & REGIONAL BLENDS ---
        {
            "id": "masala_idli_milagai_podi",
            "name": "Chettinad Idli Milagai Podi (Gunpowder with Sesame)",
            "tamilName": "செட்டிநாடு இட்லி மிளகாய்ப் பொடி",
            "category": "Spices & Seasonings", "subCategory": "Regional Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Idli Gunpowder", "Ellu Idli Podi", "Chutney Podi for Dosa", "Spicy Sesame Gunpowder"],
            "aliases": ["Aachi Idli Podi", "MTR Idli Podi", "Grand Sweets Idli Podi"],
            "brands": ["Aachi", "MTR", "Grand Sweets", "Priya", "777", "Sakthi"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [100.0, 200.0, 500.0]
        },
        {
            "id": "masala_paruppu_podi",
            "name": "Traditional Andhra / Tamil Paruppu Podi (Lentil Rice Mix)",
            "tamilName": "பாரம்பரிய பருப்புப் பொடி",
            "category": "Spices & Seasonings", "subCategory": "Regional Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Dal Rice Powder", "Kandi Podi", "Ghee Rice Paruppu Podi"],
            "aliases": ["Priya Kandi Podi", "Grand Sweets Paruppu Podi"],
            "brands": ["Priya", "Grand Sweets", "Aachi", "MTR", "777"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [100.0, 200.0]
        },
        {
            "id": "masala_karuveppilai_podi",
            "name": "Karuveppilai Podi (Curry Leaf Rice Powder)",
            "tamilName": "கருவேப்பிலைப் பொடி",
            "category": "Spices & Seasonings", "subCategory": "Regional Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Curry Leaf Chutney Powder", "Karivepaku Podi", "Iron Rich Curry Leaf Powder"],
            "aliases": ["Karuveppilai Sadam Podi", "Grand Sweets Curry Leaf Podi"],
            "brands": ["Grand Sweets", "Aachi", "Priya", "777", "MTR"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [100.0, 200.0]
        },
        {
            "id": "masala_poondu_podi",
            "name": "Poondu Podi (Garlic Chutney Powder)",
            "tamilName": "பூண்டுப் பொடி",
            "category": "Spices & Seasonings", "subCategory": "Regional Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Garlic Podi", "Vellulli Karam Podi", "Spicy Garlic Rice Powder"],
            "aliases": ["Idli Poondu Podi", "Priya Vellulli Podi"],
            "brands": ["Priya", "Grand Sweets", "Aachi", "777"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [100.0, 200.0]
        },
        {
            "id": "masala_kollu_podi",
            "name": "Kollu Podi (Horse Gram Weight Loss Rice Powder)",
            "tamilName": "கொள்ளுப் பொடி",
            "category": "Spices & Seasonings", "subCategory": "Regional Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Horse Gram Powder", "Kulthi Rice Podi", "Kollu Idli Podi"],
            "aliases": ["Fat Burner Kollu Podi", "Diet Kollu Podi"],
            "brands": ["Grand Sweets", "Aachi", "Pasumai", "Gramiyum"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [100.0, 200.0]
        },
        {
            "id": "masala_angaya_podi",
            "name": "Angaya Podi (Digestive Postpartum Herbal Rice Mix)",
            "tamilName": "அங்காயப் பொடி (செரிமான மருத்துவப் பொடி)",
            "category": "Spices & Seasonings", "subCategory": "Regional Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Post Delivery Rice Podi", "Digestive Neem Flower Sundakkai Podi", "Marundhu Podi"],
            "aliases": ["Grand Sweets Angaya Podi", "Siddha Herbal Rice Podi"],
            "brands": ["Grand Sweets", "777", "Aachi", "Bapalal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [100.0, 200.0]
        },
        {
            "id": "masala_bisi_bele_bath",
            "name": "Karnataka Bisi Bele Bath Masala Powder",
            "tamilName": "பிசி பேலே பாத் மசாலா பொடி",
            "category": "Spices & Seasonings", "subCategory": "Regional Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Hot Lentil Rice Spice Mix", "MTR Bisi Bele Bath Powder", "Karnataka BBB Masala"],
            "aliases": ["Sambar Sadam Powder Karnataka Style"],
            "brands": ["MTR", "Aachi", "Eastern", "Maiyas"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [100.0, 200.0]
        },
        {
            "id": "masala_vangi_bath",
            "name": "Vangi Bath Powder (Brinjal Spiced Rice Powder)",
            "tamilName": "வாங்கி பாத் மசாலா பொடி",
            "category": "Spices & Seasonings", "subCategory": "Regional Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Brinjal Rice Spice", "Capsicum Rice Powder", "MTR Vangi Bath"],
            "aliases": ["Baingan Chawal Masala", "Badanekayi Bath Masala"],
            "brands": ["MTR", "Aachi", "Eastern", "Maiyas"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [100.0, 200.0]
        },
        {
            "id": "masala_chettinad_curry",
            "name": "Authentic Chettinad Masala Powder",
            "tamilName": "செட்டிநாடு கறி மசாலா பொடி",
            "category": "Spices & Seasonings", "subCategory": "Regional Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Chettinad Chicken/Mutton Masala", "Karaikudi Spiced Curry Powder"],
            "aliases": ["Kalpasi Flavored Chettinad Masala", "Aachi Chettinad Masala"],
            "brands": ["Aachi", "Sakthi", "Eastern", "Tata Sampann"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0, 200.0]
        },
        {
            "id": "masala_vatha_kuzhambu_paste",
            "name": "Vatha Kuzhambu Cooking Paste / Thokku",
            "tamilName": "வத்தக் குழம்பு பேஸ்ட்",
            "category": "Pickles, Sauces & Condiments", "subCategory": "Pickles & Sauces", "productType": "condiment",
            "defaultUnit": "g", "soldBy": "bottle", "storageLocation": "Refrigerator", "minimumQuantity": 300.0,
            "commonNames": ["Sundakkai Vatha Kuzhambu Paste", "Tangy Tamarind Gravy Paste", "Manathakkali Kuzhambu Paste"],
            "aliases": ["777 Vatha Kuzhambu Paste", "Priya Vatha Kuzhambu"],
            "brands": ["777", "Grand Sweets", "Priya", "Aachi", "MTR"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "condiments", "customQuantities": [300.0, 500.0]
        },
        {
            "id": "masala_goda_maharashtra",
            "name": "Maharashtra Goda Masala Powder / Kala Masala",
            "tamilName": "கோடா மசாலா (மகாராஷ்டிரா பாரம்பரிய மசாலா)",
            "category": "Spices & Seasonings", "subCategory": "Regional Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Kala Masala", "Marathi Goda Masala", "Coconut Stone Flower Masala"],
            "aliases": ["Bedekar Goda Masala", "Kpra Goda Masala"],
            "brands": ["Bedekar", "Kpra", "Suhana", "Chitale"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0, 200.0]
        },
        {
            "id": "masala_kitchen_king_pan_indian",
            "name": "Kitchen King All-Purpose Curry Masala",
            "tamilName": "கிச்சன் கிங் அனைத்து வகை குழம்பு மசாலா",
            "category": "Spices & Seasonings", "subCategory": "Spices & Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Kitchen King Powder", "All in One Sabzi Masala", "Everest Kitchen King"],
            "aliases": ["MDH Kitchen King", "Universal Veg Curry Powder"],
            "brands": ["Everest", "MDH", "Catch", "Tata Sampann"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0, 200.0]
        },
        {
            "id": "masala_chaat_powder",
            "name": "Chaat Masala Tangy Seasoning Powder",
            "tamilName": "சாட் மசாலா தூள்",
            "category": "Spices & Seasonings", "subCategory": "Spices & Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Chaat Masala", "Street Food Sprinkle Powder", "Amchur Black Salt Seasoning"],
            "aliases": ["Everest Chaat Masala", "MDH Chunky Chaat Masala", "Catch Sprinklers"],
            "brands": ["Everest", "MDH", "Catch", "Tata Sampann"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0]
        },
        {
            "id": "masala_pav_bhaji",
            "name": "Pav Bhaji Masala Powder",
            "tamilName": "பாவ் பாஜி மசாலா தூள்",
            "category": "Spices & Seasonings", "subCategory": "Spices & Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Mumbai Pav Bhaji Spice Mix", "Everest Pav Bhaji Masala"],
            "aliases": ["Badshah Pav Bhaji Masala", "Desi Bhaji Powder"],
            "brands": ["Everest", "MDH", "Badshah", "Catch", "Tata Sampann"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0]
        },
        {
            "id": "masala_chole_chana_amritsari",
            "name": "Amritsari Chole / Chana Masala Powder",
            "tamilName": "அமிர்தசரஸ் சோலே மசாலா தூள்",
            "category": "Spices & Seasonings", "subCategory": "Spices & Masalas", "productType": "spice",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 100.0,
            "commonNames": ["Chole Masala", "Pindi Chana Masala", "Anardana Chole Spice Powder"],
            "aliases": ["MDH Chana Masala", "Everest Chole Masala"],
            "brands": ["MDH", "Everest", "Catch", "Tata Sampann"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "spices", "customQuantities": [50.0, 100.0]
        },

        # --- JAGGARIES & SWEETENERS ---
        {
            "id": "sweet_palm_jaggery_karupatti_udanangudi",
            "name": "Authentic Udanangudi Palm Jaggery / Karupatti",
            "tamilName": "உடன்குடி பனைமர கருப்பட்டி",
            "category": "Salt, Sugar & Sweeteners", "subCategory": "Salt & Sweeteners", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 0.5,
            "commonNames": ["Karupatti", "Palm Jaggery Block", "Tirunelveli Karupatti", "Black Palm Sugar"],
            "aliases": ["Organic Pure Karupatti", "Chukku Kaapi Palm Jaggery"],
            "brands": ["Gramiyum", "Udanangudi Direct", "Pasumai", "Organic Poshan", "Namma Nellu"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "salt", "customQuantities": [0.5, 1.0, 2.0]
        },
        {
            "id": "sweet_panakarkandu_palm_candy",
            "name": "Palm Sugar Candy / Panakarkandu Crystals",
            "tamilName": "பனங்கற்கண்டு படிகங்கள்",
            "category": "Salt, Sugar & Sweeteners", "subCategory": "Salt & Sweeteners", "productType": "staple",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 250.0,
            "commonNames": ["Panang Karkandu", "Palm Candy for Cold & Cough", "Taal Misri", "Natural Palm Sugar Crystals"],
            "aliases": ["Ayurvedic Palm Sugar Candy", "Milk Sweetener Panakarkandu"],
            "brands": ["Lion", "Gramiyum", "Pasumai", "Organic Tattva"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "salt", "customQuantities": [200.0, 250.0, 500.0]
        },
        {
            "id": "sweet_nattu_sakkarai_country_sugar",
            "name": "Organic Country Cane Sugar / Nattu Sakkarai",
            "tamilName": "நாட்டு சர்க்கரை (தூய கரும்பு சர்க்கரை)",
            "category": "Salt, Sugar & Sweeteners", "subCategory": "Salt & Sweeteners", "productType": "staple",
            "defaultUnit": "kg", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 1.0,
            "commonNames": ["Nattu Sakkarai", "Jaggery Powder", "Shakkar Unrefined", "Brown Cane Powder"],
            "aliases": ["Chemical-free Country Sugar", "Tea Coffee Nattu Sakkarai"],
            "brands": ["Gramiyum", "24 Mantra", "Organic Tattva", "Dhampure", "Pasumai"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "salt", "customQuantities": [0.5, 1.0, 2.0, 5.0]
        },
        {
            "id": "sweet_dhaga_mishri_rock_sugar",
            "name": "Unrefined Thread Rock Sugar / Dhaga Mishri",
            "tamilName": "நூல் கற்கண்டு / தாகா மிஸ்ரி",
            "category": "Salt, Sugar & Sweeteners", "subCategory": "Salt & Sweeteners", "productType": "staple",
            "defaultUnit": "g", "soldBy": "weight", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 250.0,
            "commonNames": ["Thread Mishri", "Kuja Mishri", "Sita Mishri", "Rock Sugar with Thread"],
            "aliases": ["Cooling Throat Mishri", "Saunf Mishri"],
            "brands": ["Urban Platter", "Natureland", "BB Royal"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "salt", "customQuantities": [250.0, 500.0]
        },
        {
            "id": "sweet_honey_wild_forest_raw",
            "name": "Raw Multi-Flora Wild Forest Honey",
            "tamilName": "தூய காட்டுத் தேன்",
            "category": "Salt, Sugar & Sweeteners", "subCategory": "Salt & Sweeteners", "productType": "staple",
            "defaultUnit": "g", "soldBy": "bottle", "storageLocation": "Kitchen Cabinet", "minimumQuantity": 500.0,
            "commonNames": ["Forest Honey Glass Jar", "Raw Pure Honey", "Nattu Thaen", "Jungle Honey Unpasteurized"],
            "aliases": ["Dabur Honey", "Patanjali Honey", "Saffola Honey 100% Pure"],
            "brands": ["Dabur", "Saffola", "Patanjali", "Zandu Pure", "Under The Mango Tree"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "salt", "customQuantities": [250.0, 500.0, 1000.0]
        },

        # --- PICKLES, VATHAL & APPALAM ---
        {
            "id": "pickle_avakaya_mango_andhra",
            "name": "Andhra Special Spicy Avakaya Mango Pickle",
            "tamilName": "ஆந்திரா ஆவக்காய் மாங்காய் ஊறுகாய்",
            "category": "Pickles, Sauces & Condiments", "subCategory": "Pickles & Sauces", "productType": "condiment",
            "defaultUnit": "g", "soldBy": "bottle", "storageLocation": "Pantry Shelf", "minimumQuantity": 300.0,
            "commonNames": ["Avakaya Pickle", "Andhra Avakkai", "Mustard Garlic Mango Pickle", "Avakai Pachadi"],
            "aliases": ["Priya Avakaya Pickle", "Authentic Spicy Avakaya"],
            "brands": ["Priya", "777", "Aachi", "Mother's Recipe", "MTR"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "condiments", "customQuantities": [300.0, 500.0, 1000.0]
        },
        {
            "id": "pickle_gongura_andhra_sorrel",
            "name": "Andhra Gongura Sorrel Leaves Pickle / Pachadi",
            "tamilName": "ஆந்திரா கோங்குரா புளிச்சக்கீரை ஊறுகாய்",
            "category": "Pickles, Sauces & Condiments", "subCategory": "Pickles & Sauces", "productType": "condiment",
            "defaultUnit": "g", "soldBy": "bottle", "storageLocation": "Pantry Shelf", "minimumQuantity": 300.0,
            "commonNames": ["Gongura Pickle", "Pulicha Keerai Thokku", "Red Sorrel Leaves Chutney"],
            "aliases": ["Priya Gongura Pachadi", "Andhra Style Gongura"],
            "brands": ["Priya", "MTR", "Aachi", "Mother's Recipe"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "condiments", "customQuantities": [300.0, 500.0]
        },
        {
            "id": "pickle_vadu_maangai_tender",
            "name": "Tender Baby Mango Pickle / Vadu Maangai",
            "tamilName": "வடு மாங்காய் ஊறுகாய்",
            "category": "Pickles, Sauces & Condiments", "subCategory": "Pickles & Sauces", "productType": "condiment",
            "defaultUnit": "g", "soldBy": "bottle", "storageLocation": "Pantry Shelf", "minimumQuantity": 300.0,
            "commonNames": ["Mavadu Pickle", "Vadu Mangai", "Brine Soaked Baby Mango", "Curd Rice Mavadu"],
            "aliases": ["777 Mavadu", "Grand Sweets Vadu Maangai"],
            "brands": ["777", "Grand Sweets", "Aachi", "Priya", "Amutha"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "condiments", "customQuantities": [300.0, 500.0]
        },
        {
            "id": "pickle_poondu_garlic_spicy",
            "name": "Spicy Whole Garlic Pickle / Poondu Oorugai",
            "tamilName": "கார பூண்டு ஊறுகாய்",
            "category": "Pickles, Sauces & Condiments", "subCategory": "Pickles & Sauces", "productType": "condiment",
            "defaultUnit": "g", "soldBy": "bottle", "storageLocation": "Pantry Shelf", "minimumQuantity": 300.0,
            "commonNames": ["Garlic Pickle", "Lehsun Ka Achar", "Vellulli Avakaya", "Poondu Pickle"],
            "aliases": ["Mother's Recipe Garlic Pickle", "Priya Garlic Pickle"],
            "brands": ["Mother's Recipe", "Priya", "777", "Aachi", "Eastern"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "condiments", "customQuantities": [300.0, 500.0]
        },
        {
            "id": "pickle_narthangai_citron",
            "name": "Citron Fruit Pickle / Narthangai Oorugai",
            "tamilName": "நார்த்தங்காய் ஊறுகாய்",
            "category": "Pickles, Sauces & Condiments", "subCategory": "Pickles & Sauces", "productType": "condiment",
            "defaultUnit": "g", "soldBy": "bottle", "storageLocation": "Pantry Shelf", "minimumQuantity": 300.0,
            "commonNames": ["Citron Pickle", "Herbal Salted Citron", "Narthangai Pickle for Digestion"],
            "aliases": ["Salted Narthangai", "777 Narthangai"],
            "brands": ["777", "Grand Sweets", "Aachi", "Priya"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "condiments", "customQuantities": [300.0, 500.0]
        },
        {
            "id": "vathal_mor_milagai_curd_chilli",
            "name": "Sun-Dried Curd Chillies / Mor Milagai",
            "tamilName": "மோர் மிளகாய் வற்றல்",
            "category": "Pickles, Sauces & Condiments", "subCategory": "Vathal & Appalam", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 100.0,
            "commonNames": ["Curd Soaked Dried Chillies", "Mor Milagai for Curd Rice", "Uppu Milagai", "Majjiga Mirapa"],
            "aliases": ["Salted Sun Chillies", "Pazhaya Sadam Mor Milagai"],
            "brands": ["777", "Grand Sweets", "Aachi", "Udhayam", "Ambika"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "condiments", "customQuantities": [100.0, 200.0, 500.0]
        },
        {
            "id": "vathal_manathakkali_black_nightshade",
            "name": "Sun-Dried Black Nightshade Berries / Manathakkali Vathal",
            "tamilName": "மணத்தக்காளி வற்றல் (குடல் புண் போக்கும்)",
            "category": "Pickles, Sauces & Condiments", "subCategory": "Vathal & Appalam", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 100.0,
            "commonNames": ["Wonderberry Vathal", "Black Nightshade Dried Berries", "Ulcer Healing Manathakkali"],
            "aliases": ["Vatha Kuzhambu Manathakkali", "Sun-dried Herbal Berries"],
            "brands": ["777", "Grand Sweets", "Aachi", "Udhayam"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "condiments", "customQuantities": [100.0, 200.0]
        },
        {
            "id": "vathal_sundakkai_turkey_berry",
            "name": "Sun-Dried Turkey Berries / Sundakkai Vathal",
            "tamilName": "சுண்டக்காய் வற்றல்",
            "category": "Pickles, Sauces & Condiments", "subCategory": "Vathal & Appalam", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 100.0,
            "commonNames": ["Turkey Berry Dried", "Sundakkai for Vatha Kuzhambu", "Salted Dried Sundakkai"],
            "aliases": ["Dewild Eggplant Berries", "777 Sundakkai Vathal"],
            "brands": ["777", "Grand Sweets", "Aachi", "Udhayam"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "condiments", "customQuantities": [100.0, 200.0]
        },
        {
            "id": "vadagam_thalippu_onion",
            "name": "Traditional Seasoning Onion Vadagam / Thalippu Vadagam",
            "tamilName": "தாளிப்பு வெங்காய வடகம்",
            "category": "Pickles, Sauces & Condiments", "subCategory": "Vathal & Appalam", "productType": "staple",
            "defaultUnit": "g", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 100.0,
            "commonNames": ["Seasoning Vadagam", "Vengaya Vadagam", "Sambar Fish Curry Tempering Vadagam"],
            "aliases": ["Sun-dried Shallot Seasoning Ball", "Chettinad Vadagam"],
            "brands": ["Grand Sweets", "777", "Aachi", "Ambika"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": True, "isPackaged": True,
            "iconKey": "condiments", "customQuantities": [100.0, 200.0]
        },
        {
            "id": "appalam_madras_plain_crispy",
            "name": "Traditional Madras Crispy Urad Appalam",
            "tamilName": "பாரம்பரிய மெட்ராஸ் உளுந்து அப்பளம்",
            "category": "Pickles, Sauces & Condiments", "subCategory": "Vathal & Appalam", "productType": "staple",
            "defaultUnit": "pack", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Madras Appalam", "Papadum", "South Indian Lunch Appalam", "Ulundhu Appalam"],
            "aliases": ["Ambika Madras Appalam", "Kerala Papadum", "Double Horse Appalam"],
            "brands": ["Ambika", "Double Horse", "MTR", "Aachi", "Udhayam"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "condiments", "customQuantities": [1.0, 2.0, 5.0]
        },
        {
            "id": "papad_lijjat_moong_pepper",
            "name": "Lijjat Moong Dal Pepper Papad",
            "tamilName": "லிஜ்ஜத் பாசிப்பருப்பு மிளகு அப்பளம்",
            "category": "Pickles, Sauces & Condiments", "subCategory": "Vathal & Appalam", "productType": "staple",
            "defaultUnit": "pack", "soldBy": "package", "storageLocation": "Pantry Shelf", "minimumQuantity": 1.0,
            "commonNames": ["Lijjat Papad", "Moong Dal Black Pepper Papad", "Roasted Papad"],
            "aliases": ["Shri Mahila Griha Udyog Lijjat", "Punjabi Black Pepper Papad"],
            "brands": ["Lijjat", "Bikanervala", "Haldiram", "MTR"],
            "barcodeSupport": True, "barcodeType": "EAN_13", "barcodes": [], "isLoose": False, "isPackaged": True,
            "iconKey": "condiments", "customQuantities": [1.0, 2.0, 5.0]
        },
    ]
    return items

