package com.homestock.modules.voice.dto;

public enum VoiceIntent {
    ADD_SHOPPING_ITEM,
    REMOVE_SHOPPING_ITEM,
    COMPLETE_SHOPPING_ITEM,

    UPDATE_STOCK,
    STOCK_IN,
    STOCK_OUT,

    GET_ITEM_STATUS,
    GET_SHOPPING_LIST,
    GET_LOW_STOCK_ITEMS,
    GET_EXPIRING_ITEMS,

    SEARCH_INVENTORY,
    ADD_INVENTORY_ITEM,
    UPDATE_INVENTORY_ITEM,

    OPEN_SHOPPING_LIST,
    OPEN_INVENTORY,
    OPEN_ANALYTICS,
    SMART_PRICE_CHECK,

    UNKNOWN
}
