package com.homestock.modules.voice.dto;

public enum VoiceIntent {
    // Shopping List
    ADD_SHOPPING_ITEM,
    REMOVE_SHOPPING_ITEM,
    UPDATE_SHOPPING_ITEM,
    COMPLETE_SHOPPING_ITEM,
    CLEAR_SHOPPING_LIST,
    GET_SHOPPING_LIST,

    // Inventory
    UPDATE_STOCK,
    STOCK_IN,
    STOCK_OUT,
    ADD_INVENTORY_ITEM,
    UPDATE_INVENTORY_ITEM,
    REMOVE_INVENTORY_ITEM,
    GET_ITEM_STATUS,
    SEARCH_INVENTORY,
    GET_LOW_STOCK_ITEMS,
    GET_EXPIRING_ITEMS,

    // Product & Search
    SEARCH_PRODUCT,
    GET_PRODUCT_DETAILS,
    SMART_PRICE_CHECK,

    // Navigation
    OPEN_SHOPPING_LIST,
    OPEN_INVENTORY,
    OPEN_ANALYTICS,

    // Fallback
    UNKNOWN
}
